/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import tela.dialog.PanelAdicionarCurso;
import tela.dialog.PanelAtualizarCurso;
import controle.ControleTelaDisciplina;
import java.awt.event.ItemEvent;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import tela.dialog.PanelAdicionarDisciplina;
import tela.dialog.PanelAtualizarDisciplina;
import java.awt.Font;

/**
 *
 * @author Diana
 */
public class InternoJfTelaDisciplina extends javax.swing.JInternalFrame {

    private final ControleTelaDisciplina controle;
    private PanelAdicionarCurso dialogAdicionar;
    private PanelAtualizarCurso dialogAtualizar;
    private PanelAdicionarDisciplina dialogAdicionarDisciplina;
    private PanelAtualizarDisciplina dialogAtualizarDisciplina;

    /**
     * Creates new form InternoJfTelaDisicplina
     */

    public InternoJfTelaDisciplina() {
        initComponents();
        controle = new ControleTelaDisciplina(this, dialogAdicionar, dialogAtualizar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDisciplina = new javax.swing.JPanel();
        jLabelDisciplinas = new javax.swing.JLabel();
        jLabelCurso = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableDisciplinas = new javax.swing.JTable();
        jComboBoxCurso = new javax.swing.JComboBox<>();
        jButtonAdicionarCurso = new javax.swing.JButton();
        jButtonRemoverCurso = new javax.swing.JButton();
        jButtonEditarDisciplina = new javax.swing.JButton();
        jButtonAdicionarDisciplina = new javax.swing.JButton();
        jButtonRemoverDisciplina = new javax.swing.JButton();
        jButtonEditarCurso = new javax.swing.JButton();

        setBackground(new java.awt.Color(69, 69, 71));
        setBorder(null);
        setMaximumSize(new java.awt.Dimension(955, 575));
        setPreferredSize(new java.awt.Dimension(955, 575));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelDisciplina.setBackground(new java.awt.Color(69, 69, 71));
        jPanelDisciplina.setMaximumSize(new java.awt.Dimension(915, 544));

        jLabelDisciplinas.setBackground(new java.awt.Color(227, 162, 26));
        jLabelDisciplinas.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        jLabelDisciplinas.setText(" Cursos e Disciplinas");
        jLabelDisciplinas.setOpaque(true);

        jLabelCurso.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelCurso.setForeground(new java.awt.Color(240, 240, 240));
        jLabelCurso.setText("Curso");

        jScrollPane4.setBackground(new java.awt.Color(69, 69, 71));
        jScrollPane4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 69, 71), 1, true));
        jScrollPane4.setViewportBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 69, 71), 1, true));
        jScrollPane4.getViewport().setOpaque(false);

        jTableDisciplinas.setBackground(new java.awt.Color(69, 69, 71));
        jTableDisciplinas.setFont(new java.awt.Font("Dialog", 0, 14));
        jTableDisciplinas.setForeground(new java.awt.Color(255, 255, 255));
        jTableDisciplinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Disciplina", "Data de Início", "Data de Término", "Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sab"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDisciplinas.setToolTipText("");
        jTableDisciplinas.setFocusable(false);
        jTableDisciplinas.setOpaque(false);
        jTableDisciplinas.setRowHeight(30);
        jTableDisciplinas.setSelectionBackground(new java.awt.Color(218, 83, 44));
        jTableDisciplinas.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTableDisciplinas.setShowVerticalLines(false);
        jTableDisciplinas.getTableHeader().setReorderingAllowed(false);
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) jTableDisciplinas
        .getDefaultRenderer(JLabel.class);
        renderer.setHorizontalAlignment(SwingConstants.LEFT);

        //Tentando alterar alinhamento de colunas específicas
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        jTableDisciplinas.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        jTableDisciplinas.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        DefaultTableCellRenderer headerRendererCenter = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new java.awt.Color(227,162,26));
        headerRendererCenter.setBackground(new java.awt.Color(227,162,26));
        headerRendererCenter.setHorizontalAlignment(SwingConstants.CENTER);
        jTableDisciplinas.getColumnModel().getColumn(0).setHeaderRenderer(headerRenderer);
        for (int i = 1; i < jTableDisciplinas.getModel().getColumnCount(); i++) {
            jTableDisciplinas.getColumnModel().getColumn(i).setHeaderRenderer(headerRendererCenter);
        }
        jTableDisciplinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDisciplinasMouseClicked(evt);
            }
        });
        jTableDisciplinas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableDisciplinasKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTableDisciplinas);
        if (jTableDisciplinas.getColumnModel().getColumnCount() > 0) {
            jTableDisciplinas.getColumnModel().getColumn(1).setMinWidth(120);
            jTableDisciplinas.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTableDisciplinas.getColumnModel().getColumn(1).setMaxWidth(120);
            jTableDisciplinas.getColumnModel().getColumn(2).setMinWidth(120);
            jTableDisciplinas.getColumnModel().getColumn(2).setPreferredWidth(120);
            jTableDisciplinas.getColumnModel().getColumn(2).setMaxWidth(120);
            jTableDisciplinas.getColumnModel().getColumn(3).setMinWidth(36);
            jTableDisciplinas.getColumnModel().getColumn(3).setPreferredWidth(36);
            jTableDisciplinas.getColumnModel().getColumn(3).setMaxWidth(36);
            jTableDisciplinas.getColumnModel().getColumn(4).setMinWidth(36);
            jTableDisciplinas.getColumnModel().getColumn(4).setPreferredWidth(36);
            jTableDisciplinas.getColumnModel().getColumn(4).setMaxWidth(36);
            jTableDisciplinas.getColumnModel().getColumn(5).setMinWidth(36);
            jTableDisciplinas.getColumnModel().getColumn(5).setPreferredWidth(36);
            jTableDisciplinas.getColumnModel().getColumn(5).setMaxWidth(36);
            jTableDisciplinas.getColumnModel().getColumn(6).setMinWidth(36);
            jTableDisciplinas.getColumnModel().getColumn(6).setPreferredWidth(36);
            jTableDisciplinas.getColumnModel().getColumn(6).setMaxWidth(36);
            jTableDisciplinas.getColumnModel().getColumn(7).setMinWidth(36);
            jTableDisciplinas.getColumnModel().getColumn(7).setPreferredWidth(36);
            jTableDisciplinas.getColumnModel().getColumn(7).setMaxWidth(36);
            jTableDisciplinas.getColumnModel().getColumn(8).setMinWidth(36);
            jTableDisciplinas.getColumnModel().getColumn(8).setPreferredWidth(36);
            jTableDisciplinas.getColumnModel().getColumn(8).setMaxWidth(36);
            jTableDisciplinas.getColumnModel().getColumn(9).setMinWidth(36);
            jTableDisciplinas.getColumnModel().getColumn(9).setPreferredWidth(36);
            jTableDisciplinas.getColumnModel().getColumn(9).setMaxWidth(36);
        }

        jComboBoxCurso.setBackground(new java.awt.Color(69, 69, 69));
        jComboBoxCurso.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jComboBoxCurso.setForeground(new java.awt.Color(240, 240, 240));
        jComboBoxCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 162, 26)));
        jComboBoxCurso.setFocusable(false);
        jComboBoxCurso.setOpaque(false);
        jComboBoxCurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCursoItemStateChanged(evt);
            }
        });

        jButtonAdicionarCurso.setBackground(new java.awt.Color(227, 162, 26));
        jButtonAdicionarCurso.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jButtonAdicionarCurso.setForeground(new java.awt.Color(240, 240, 240));
        jButtonAdicionarCurso.setText("Adicionar");
        jButtonAdicionarCurso.setFocusable(false);
        jButtonAdicionarCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAdicionarCursoMouseClicked(evt);
            }
        });

        jButtonRemoverCurso.setBackground(new java.awt.Color(227, 162, 26));
        jButtonRemoverCurso.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jButtonRemoverCurso.setForeground(new java.awt.Color(240, 240, 240));
        jButtonRemoverCurso.setText("Remover");
        jButtonRemoverCurso.setFocusable(false);
        jButtonRemoverCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRemoverCursoMouseClicked(evt);
            }
        });

        jButtonEditarDisciplina.setBackground(new java.awt.Color(227, 162, 26));
        jButtonEditarDisciplina.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jButtonEditarDisciplina.setForeground(new java.awt.Color(240, 240, 240));
        jButtonEditarDisciplina.setText("Editar Disciplina");
        jButtonEditarDisciplina.setFocusable(false);
        jButtonEditarDisciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditarDisciplinaMouseClicked(evt);
            }
        });

        jButtonAdicionarDisciplina.setBackground(new java.awt.Color(227, 162, 26));
        jButtonAdicionarDisciplina.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jButtonAdicionarDisciplina.setForeground(new java.awt.Color(240, 240, 240));
        jButtonAdicionarDisciplina.setText("Adicionar Disciplina");
        jButtonAdicionarDisciplina.setFocusable(false);
        jButtonAdicionarDisciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAdicionarDisciplinaMouseClicked(evt);
            }
        });

        jButtonRemoverDisciplina.setBackground(new java.awt.Color(227, 162, 26));
        jButtonRemoverDisciplina.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jButtonRemoverDisciplina.setForeground(new java.awt.Color(240, 240, 240));
        jButtonRemoverDisciplina.setText("Remover Disciplina");
        jButtonRemoverDisciplina.setFocusable(false);
        jButtonRemoverDisciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRemoverDisciplinaMouseClicked(evt);
            }
        });

        jButtonEditarCurso.setBackground(new java.awt.Color(227, 162, 26));
        jButtonEditarCurso.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jButtonEditarCurso.setForeground(new java.awt.Color(240, 240, 240));
        jButtonEditarCurso.setText("Editar");
        jButtonEditarCurso.setFocusable(false);
        jButtonEditarCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditarCursoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelDisciplinaLayout = new javax.swing.GroupLayout(jPanelDisciplina);
        jPanelDisciplina.setLayout(jPanelDisciplinaLayout);
        jPanelDisciplinaLayout.setHorizontalGroup(
            jPanelDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelDisciplinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelDisciplinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDisciplinaLayout.createSequentialGroup()
                        .addComponent(jButtonAdicionarDisciplina)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditarDisciplina)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRemoverDisciplina))
                    .addGroup(jPanelDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelDisciplinaLayout.createSequentialGroup()
                            .addComponent(jLabelCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBoxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonAdicionarCurso)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonEditarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonRemoverCurso))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanelDisciplinaLayout.setVerticalGroup(
            jPanelDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDisciplinaLayout.createSequentialGroup()
                .addComponent(jLabelDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionarCurso)
                    .addComponent(jButtonRemoverCurso)
                    .addComponent(jButtonEditarCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdicionarDisciplina)
                    .addComponent(jButtonEditarDisciplina)
                    .addComponent(jButtonRemoverDisciplina))
                .addGap(43, 43, 43))
        );

        getContentPane().add(jPanelDisciplina, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditarCursoMouseClicked
        if (this.getjComboBoxCurso().getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Não há itens para serem editados.");
        } else {
            dialogAtualizar = new PanelAtualizarCurso(this, (JFrame) this.getTopLevelAncestor());
        }
    }//GEN-LAST:event_jButtonEditarCursoMouseClicked

    private void jButtonRemoverDisciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRemoverDisciplinaMouseClicked
        if (jTableDisciplinas.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Nenhuma disciplina foi selecionada");
        } else {
            try {
                controle.removerDisciplina();
            } catch (ParseException ex) {
                Logger.getLogger(InternoJfTelaDisciplina.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonRemoverDisciplinaMouseClicked

    private void jButtonAdicionarDisciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAdicionarDisciplinaMouseClicked
        if (this.getjComboBoxCurso().getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Adicione um curso para poder inserir disciplinas");
        } else {
            dialogAdicionarDisciplina = new PanelAdicionarDisciplina(this, (JFrame) this.getTopLevelAncestor());
        }
    }//GEN-LAST:event_jButtonAdicionarDisciplinaMouseClicked

    private void jButtonEditarDisciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditarDisciplinaMouseClicked
        if (jTableDisciplinas.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Nenhuma disciplina foi selecionada");
        } else {
            dialogAtualizarDisciplina = new PanelAtualizarDisciplina(this, (JFrame) this.getTopLevelAncestor());
        }
    }//GEN-LAST:event_jButtonEditarDisciplinaMouseClicked

    private void jButtonRemoverCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRemoverCursoMouseClicked
        try {
            controle.removerCurso();
        } catch (ParseException ex) {
            Logger.getLogger(InternoJfTelaDisciplina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRemoverCursoMouseClicked

    private void jButtonAdicionarCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAdicionarCursoMouseClicked

        dialogAdicionar = new PanelAdicionarCurso(this, (JFrame) this.getTopLevelAncestor());
    }//GEN-LAST:event_jButtonAdicionarCursoMouseClicked

    private void jComboBoxCursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCursoItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            try {
                controle.exibirDisciplinas();
            } catch (ParseException ex) {
                Logger.getLogger(InternoJfTelaDisciplina.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jComboBoxCursoItemStateChanged

    private void jTableDisciplinasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableDisciplinasKeyReleased
        // TODO add your handling code here:
        //        controleEventoTabela();
    }//GEN-LAST:event_jTableDisciplinasKeyReleased

    private void jTableDisciplinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDisciplinasMouseClicked
        // TODO add your handling code here:

        //        controleEventoTabela();
    }//GEN-LAST:event_jTableDisciplinasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarCurso;
    private javax.swing.JButton jButtonAdicionarDisciplina;
    private javax.swing.JButton jButtonEditarCurso;
    private javax.swing.JButton jButtonEditarDisciplina;
    private javax.swing.JButton jButtonRemoverCurso;
    private javax.swing.JButton jButtonRemoverDisciplina;
    private javax.swing.JComboBox<String> jComboBoxCurso;
    private javax.swing.JLabel jLabelCurso;
    private javax.swing.JLabel jLabelDisciplinas;
    private javax.swing.JPanel jPanelDisciplina;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableDisciplinas;
    // End of variables declaration//GEN-END:variables

    public JTable getjTableDisciplinas() {
        return jTableDisciplinas;
    }

    public void setjTableDisciplinas(JTable jTableDisciplinas) {
        this.jTableDisciplinas = jTableDisciplinas;
    }

    public JComboBox<String> getjComboBoxCurso() {
        return jComboBoxCurso;
    }

    public void setjComboBoxCurso(JComboBox<String> jComboBoxCurso) {
        this.jComboBoxCurso = jComboBoxCurso;
    }

    public PanelAdicionarCurso getDialog() {
        return dialogAdicionar;
    }

    public JButton getjButtonAdicionarDisciplina() {
        return jButtonAdicionarDisciplina;
    }

    public void setjButtonAdicionarDisciplina(JButton jButtonAdicionarDisciplina) {
        this.jButtonAdicionarDisciplina = jButtonAdicionarDisciplina;
    }

    public JButton getjButtonEditarDisciplina() {
        return jButtonEditarDisciplina;
    }

    public void setjButtonEditarDisciplina(JButton jButtonEditarDisciplina) {
        this.jButtonEditarDisciplina = jButtonEditarDisciplina;
    }

    public JButton getjButtonRemoverDisciplina() {
        return jButtonRemoverDisciplina;
    }

    public void setjButtonRemoverDisciplina(JButton jButtonRemoverDisciplina) {
        this.jButtonRemoverDisciplina = jButtonRemoverDisciplina;
    }
}
