/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import controle.ControlerTelaConfigGeral;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Diana
 */
public class InternoJfTelaConfGeral extends javax.swing.JInternalFrame {

    private final ControlerTelaConfigGeral controler;

    /**
     * Creates new form InternoJfTelaDisicplina
     */
    public InternoJfTelaConfGeral() {
        initComponents();
         controler = new ControlerTelaConfigGeral(this);
         iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupReceberMensagem = new javax.swing.ButtonGroup();
        buttonGroupCampo = new javax.swing.ButtonGroup();
        buttonGroupFrase = new javax.swing.ButtonGroup();
        jPanelTarefas = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTabbedPaneConfigGeral = new javax.swing.JTabbedPane();
        jPanelConfigUsers = new javax.swing.JPanel();
        jTextFieldPesquisarUsuario = new javax.swing.JTextField();
        jLabelBotaoPesquisar = new javax.swing.JLabel();
        jRadioButtonBuscaCodigo = new javax.swing.JRadioButton();
        jRadioButtonTipo = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();
        jPanelInicGerencia = new javax.swing.JPanel();
        jButtonNovoUsuario = new javax.swing.JButton();
        jButtonExcluirUsuario = new javax.swing.JButton();
        jButtonEditarUsuario = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextNome = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jTextUser = new javax.swing.JTextField();
        jPasswordSenha = new javax.swing.JPasswordField();
        jLabelMensagemDia = new javax.swing.JLabel();
        jRadioButtonReceMensagem = new javax.swing.JRadioButton();
        jRadioButtonNReceMensage = new javax.swing.JRadioButton();
        jTextCodigouser = new javax.swing.JTextField();
        jComboBoxTipoUser = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jRadioButtonNome = new javax.swing.JRadioButton();
        jPanelConfigMensagem = new javax.swing.JPanel();
        jTextFieldPesquisarMensagem = new javax.swing.JTextField();
        jRadioButtonFrase = new javax.swing.JRadioButton();
        jRadioButtoCodigoFrase = new javax.swing.JRadioButton();
        jLabeBotaolPesquisaMensagem = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextCodiFrase = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaFrase = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableMensagem = new javax.swing.JTable();
        jPanelInicGerencia1 = new javax.swing.JPanel();
        jButtonEditarMensage = new javax.swing.JButton();
        jButtonNovoMensa = new javax.swing.JButton();
        jButtonExcluirMensagem = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(69, 69, 71));
        setBorder(null);
        setMaximumSize(new java.awt.Dimension(955, 575));
        setPreferredSize(new java.awt.Dimension(955, 575));

        jPanelTarefas.setBackground(new java.awt.Color(69, 69, 71));

        jLabel11.setBackground(new java.awt.Color(153, 180, 51));
        jLabel11.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        jLabel11.setText("Configurações Administrador");
        jLabel11.setMaximumSize(new java.awt.Dimension(318, 45));
        jLabel11.setMinimumSize(new java.awt.Dimension(318, 45));
        jLabel11.setOpaque(true);
        jLabel11.setPreferredSize(new java.awt.Dimension(318, 45));

        jTabbedPaneConfigGeral.setBackground(new java.awt.Color(69, 69, 71));
        jTabbedPaneConfigGeral.setForeground(new java.awt.Color(153, 180, 51));

        jPanelConfigUsers.setBackground(new java.awt.Color(69, 69, 71));

        jTextFieldPesquisarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPesquisarUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 2, true));
        jTextFieldPesquisarUsuario.setOpaque(false);
        jTextFieldPesquisarUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarUsuarioKeyReleased(evt);
            }
        });

        jLabelBotaoPesquisar.setBackground(new java.awt.Color(69, 69, 71));
        jLabelBotaoPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBotaoPesquisar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBotaoPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Search16.png"))); // NOI18N
        jLabelBotaoPesquisar.setOpaque(true);

        buttonGroupCampo.add(jRadioButtonBuscaCodigo);
        jRadioButtonBuscaCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonBuscaCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonBuscaCodigo.setText("Código");
        jRadioButtonBuscaCodigo.setOpaque(false);

        buttonGroupCampo.add(jRadioButtonTipo);
        jRadioButtonTipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonTipo.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonTipo.setSelected(true);
        jRadioButtonTipo.setText("Tipo");
        jRadioButtonTipo.setOpaque(false);

        jScrollPane4.setBackground(new java.awt.Color(69, 69, 71));
        jScrollPane4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 69, 71), 1, true));
        jScrollPane4.setViewportBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 69, 71), 1, true));
        jScrollPane4.getViewport().setOpaque(false);

        jTableUsuario.setBackground(new java.awt.Color(69, 69, 71));
        jTableUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód", "Nome", "Email", "usuário", "Senha", "tipo", "Men"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUsuario.setToolTipText("");
        jTableUsuario.setFocusable(false);
        jTableUsuario.setOpaque(false);
        jTableUsuario.setRowHeight(30);
        jTableUsuario.setRowMargin(3);
        jTableUsuario.setSelectionBackground(new java.awt.Color(66, 244, 158));
        jTableUsuario.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTableUsuario.setShowVerticalLines(false);
        jTableUsuario.getTableHeader().setReorderingAllowed(false);
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) jTableUsuario
        .getDefaultRenderer(JLabel.class);
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new java.awt.Color(153,180,51));
        //60, 74, 178
        headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < jTableUsuario.getModel().getColumnCount(); i++) {
            jTableUsuario.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        jTableUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuarioMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableUsuario);
        if (jTableUsuario.getColumnModel().getColumnCount() > 0) {
            jTableUsuario.getColumnModel().getColumn(0).setMinWidth(30);
            jTableUsuario.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTableUsuario.getColumnModel().getColumn(0).setMaxWidth(30);
            jTableUsuario.getColumnModel().getColumn(3).setMinWidth(100);
            jTableUsuario.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTableUsuario.getColumnModel().getColumn(3).setMaxWidth(150);
            jTableUsuario.getColumnModel().getColumn(4).setMinWidth(100);
            jTableUsuario.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTableUsuario.getColumnModel().getColumn(4).setMaxWidth(100);
            jTableUsuario.getColumnModel().getColumn(5).setMinWidth(100);
            jTableUsuario.getColumnModel().getColumn(5).setPreferredWidth(150);
            jTableUsuario.getColumnModel().getColumn(5).setMaxWidth(150);
            jTableUsuario.getColumnModel().getColumn(6).setMinWidth(30);
            jTableUsuario.getColumnModel().getColumn(6).setPreferredWidth(30);
            jTableUsuario.getColumnModel().getColumn(6).setMaxWidth(30);
        }

        jPanelInicGerencia.setBackground(new java.awt.Color(69, 69, 71));
        jPanelInicGerencia.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 6, true), "OPÇÕES", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelInicGerencia.setPreferredSize(new java.awt.Dimension(311, 428));

        jButtonNovoUsuario.setBackground(new java.awt.Color(51, 204, 255));
        jButtonNovoUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNovoUsuario.setText("Novo");
        jButtonNovoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventoNovoUsuario(evt);
            }
        });

        jButtonExcluirUsuario.setBackground(new java.awt.Color(255, 51, 51));
        jButtonExcluirUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExcluirUsuario.setText("Excluir Usuário");
        jButtonExcluirUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirUsuarioActionPerformed(evt);
            }
        });

        jButtonEditarUsuario.setBackground(new java.awt.Color(181, 92, 28));
        jButtonEditarUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEditarUsuario.setText("Editar");
        jButtonEditarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInicGerenciaLayout = new javax.swing.GroupLayout(jPanelInicGerencia);
        jPanelInicGerencia.setLayout(jPanelInicGerenciaLayout);
        jPanelInicGerenciaLayout.setHorizontalGroup(
            jPanelInicGerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicGerenciaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelInicGerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonNovoUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExcluirUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelInicGerenciaLayout.setVerticalGroup(
            jPanelInicGerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicGerenciaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButtonNovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jButtonEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jButtonExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        jPanel2.setBackground(new java.awt.Color(69, 69, 71));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 6, true), "DADOS USUÁRIO", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(570, 529));

        jTextNome.setEditable(false);
        jTextNome.setBackground(new java.awt.Color(69, 69, 71));
        jTextNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextNome.setForeground(new java.awt.Color(255, 255, 255));
        jTextNome.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 1, true), "Nome", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jTextNome.setMaximumSize(new java.awt.Dimension(385, 40));
        jTextNome.setPreferredSize(new java.awt.Dimension(385, 40));

        jTextEmail.setEditable(false);
        jTextEmail.setBackground(new java.awt.Color(69, 69, 71));
        jTextEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextEmail.setForeground(new java.awt.Color(255, 255, 255));
        jTextEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 1, true), "Email", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jTextEmail.setMaximumSize(new java.awt.Dimension(385, 40));
        jTextEmail.setPreferredSize(new java.awt.Dimension(385, 40));

        jTextUser.setEditable(false);
        jTextUser.setBackground(new java.awt.Color(69, 69, 71));
        jTextUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextUser.setForeground(new java.awt.Color(255, 255, 255));
        jTextUser.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 1, true), "Usuário", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jTextUser.setMaximumSize(new java.awt.Dimension(385, 40));
        jTextUser.setPreferredSize(new java.awt.Dimension(385, 40));

        jPasswordSenha.setEditable(false);
        jPasswordSenha.setBackground(new java.awt.Color(69, 69, 71));
        jPasswordSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPasswordSenha.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 1, true), "Senha", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPasswordSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordSenhaActionPerformed(evt);
            }
        });

        jLabelMensagemDia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelMensagemDia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMensagemDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMensagemDia.setText("Receber mensagem do dia?");

        jRadioButtonReceMensagem.setBackground(new java.awt.Color(69, 69, 71));
        buttonGroupReceberMensagem.add(jRadioButtonReceMensagem);
        jRadioButtonReceMensagem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonReceMensagem.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonReceMensagem.setText("Sim");
        jRadioButtonReceMensagem.setEnabled(false);

        jRadioButtonNReceMensage.setBackground(new java.awt.Color(69, 69, 71));
        buttonGroupReceberMensagem.add(jRadioButtonNReceMensage);
        jRadioButtonNReceMensage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonNReceMensage.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonNReceMensage.setText("Não");
        jRadioButtonNReceMensage.setEnabled(false);

        jTextCodigouser.setEditable(false);
        jTextCodigouser.setBackground(new java.awt.Color(69, 69, 71));
        jTextCodigouser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextCodigouser.setForeground(new java.awt.Color(255, 255, 255));
        jTextCodigouser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextCodigouser.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 1, true), "Código", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jTextCodigouser.setMaximumSize(new java.awt.Dimension(385, 40));
        jTextCodigouser.setPreferredSize(new java.awt.Dimension(385, 40));

        jComboBoxTipoUser.setBackground(new java.awt.Color(69, 69, 69));
        jComboBoxTipoUser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBoxTipoUser.setForeground(new java.awt.Color(240, 240, 240));
        jComboBoxTipoUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Estudante" }));
        jComboBoxTipoUser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 180, 51)), "Tipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jComboBoxTipoUser.setEnabled(false);
        jComboBoxTipoUser.setFocusable(false);
        jComboBoxTipoUser.setOpaque(false);
        jComboBoxTipoUser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoUserItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextUser, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPasswordSenha))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelMensagemDia)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonReceMensagem)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonNReceMensage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextCodigouser, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxTipoUser, 0, 251, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMensagemDia)
                            .addComponent(jRadioButtonReceMensagem)
                            .addComponent(jRadioButtonNReceMensage)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextCodigouser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxTipoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/morpheus.png"))); // NOI18N

        buttonGroupCampo.add(jRadioButtonNome);
        jRadioButtonNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonNome.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonNome.setText("Nome");
        jRadioButtonNome.setOpaque(false);

        javax.swing.GroupLayout jPanelConfigUsersLayout = new javax.swing.GroupLayout(jPanelConfigUsers);
        jPanelConfigUsers.setLayout(jPanelConfigUsersLayout);
        jPanelConfigUsersLayout.setHorizontalGroup(
            jPanelConfigUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfigUsersLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jRadioButtonBuscaCodigo)
                .addGap(15, 15, 15)
                .addComponent(jRadioButtonNome)
                .addGap(15, 15, 15)
                .addComponent(jRadioButtonTipo)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldPesquisarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBotaoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConfigUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConfigUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanelConfigUsersLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanelInicGerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanelConfigUsersLayout.setVerticalGroup(
            jPanelConfigUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConfigUsersLayout.createSequentialGroup()
                .addGroup(jPanelConfigUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConfigUsersLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConfigUsersLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelConfigUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBotaoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelConfigUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldPesquisarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRadioButtonTipo)
                                .addComponent(jRadioButtonNome)
                                .addComponent(jRadioButtonBuscaCodigo)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConfigUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelInicGerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jTabbedPaneConfigGeral.addTab("Gerênciar todos usuários", jPanelConfigUsers);

        jPanelConfigMensagem.setBackground(new java.awt.Color(69, 69, 71));

        jTextFieldPesquisarMensagem.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPesquisarMensagem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 2, true));
        jTextFieldPesquisarMensagem.setOpaque(false);
        jTextFieldPesquisarMensagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BuscaMensagem(evt);
            }
        });

        buttonGroupFrase.add(jRadioButtonFrase);
        jRadioButtonFrase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonFrase.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonFrase.setSelected(true);
        jRadioButtonFrase.setText("Frase");
        jRadioButtonFrase.setOpaque(false);

        buttonGroupFrase.add(jRadioButtoCodigoFrase);
        jRadioButtoCodigoFrase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtoCodigoFrase.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtoCodigoFrase.setText("Código");
        jRadioButtoCodigoFrase.setOpaque(false);

        jLabeBotaolPesquisaMensagem.setBackground(new java.awt.Color(69, 69, 71));
        jLabeBotaolPesquisaMensagem.setForeground(new java.awt.Color(255, 255, 255));
        jLabeBotaolPesquisaMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeBotaolPesquisaMensagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Search16.png"))); // NOI18N
        jLabeBotaolPesquisaMensagem.setOpaque(true);

        jPanel3.setBackground(new java.awt.Color(69, 69, 71));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 6, true), "FRASE", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(570, 529));

        jTextCodiFrase.setEditable(false);
        jTextCodiFrase.setBackground(new java.awt.Color(69, 69, 71));
        jTextCodiFrase.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jTextCodiFrase.setForeground(new java.awt.Color(255, 255, 255));
        jTextCodiFrase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextCodiFrase.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 1, true), "Código", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jTextCodiFrase.setMaximumSize(new java.awt.Dimension(385, 40));
        jTextCodiFrase.setPreferredSize(new java.awt.Dimension(385, 40));

        jScrollPane6.setBorder(null);

        jTextAreaFrase.setEditable(false);
        jTextAreaFrase.setBackground(new java.awt.Color(69, 69, 71));
        jTextAreaFrase.setColumns(20);
        jTextAreaFrase.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextAreaFrase.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaFrase.setRows(5);
        jTextAreaFrase.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 1, true), "Frase", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jTextAreaFrase.setWrapStyleWord(true);
        jTextAreaFrase.setLineWrap(true);
        jScrollPane6.setViewportView(jTextAreaFrase);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextCodiFrase, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextCodiFrase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane5.setBackground(new java.awt.Color(69, 69, 71));
        jScrollPane5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 69, 71), 1, true));
        jScrollPane5.setViewportBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 69, 71), 1, true));
        jScrollPane5.getViewport().setOpaque(false);

        jTableMensagem.setBackground(new java.awt.Color(69, 69, 71));
        jTableMensagem.setForeground(new java.awt.Color(255, 255, 255));
        jTableMensagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Mensagem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMensagem.setToolTipText("");
        jTableMensagem.setFocusable(false);
        jTableMensagem.setIntercellSpacing(new java.awt.Dimension(1, 3));
        jTableMensagem.setOpaque(false);
        jTableMensagem.setRowHeight(30);
        jTableMensagem.setSelectionBackground(new java.awt.Color(66, 244, 158));
        jTableMensagem.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTableMensagem.setShowVerticalLines(false);
        jTableMensagem.getTableHeader().setReorderingAllowed(false);
        DefaultTableCellRenderer renderere = (DefaultTableCellRenderer) jTableMensagem
        .getDefaultRenderer(JLabel.class);
        renderere.setHorizontalAlignment(SwingConstants.CENTER);
        DefaultTableCellRenderer headerRenderere = new DefaultTableCellRenderer();
        headerRenderere.setBackground(new java.awt.Color(153,180,51));
        //60, 74, 178
        headerRenderere.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < jTableMensagem.getModel().getColumnCount(); i++) {
            jTableMensagem.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderere);
        }
        jTableMensagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMensagemMouseClicked(evt);
            }
        });
        jTableMensagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableMensagemKeyReleased(evt);
            }
        });
        jScrollPane5.setViewportView(jTableMensagem);
        if (jTableMensagem.getColumnModel().getColumnCount() > 0) {
            jTableMensagem.getColumnModel().getColumn(0).setMinWidth(30);
            jTableMensagem.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableMensagem.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanelInicGerencia1.setBackground(new java.awt.Color(69, 69, 71));
        jPanelInicGerencia1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 6, true), "OPÇÕES", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelInicGerencia1.setPreferredSize(new java.awt.Dimension(311, 428));

        jButtonEditarMensage.setBackground(new java.awt.Color(181, 92, 28));
        jButtonEditarMensage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEditarMensage.setText("EDITAR");
        jButtonEditarMensage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditarMensage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarMensageActionPerformed(evt);
            }
        });

        jButtonNovoMensa.setBackground(new java.awt.Color(153, 180, 51));
        jButtonNovoMensa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNovoMensa.setText("NOVO");
        jButtonNovoMensa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNovoMensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoMensaActionPerformed(evt);
            }
        });

        jButtonExcluirMensagem.setBackground(new java.awt.Color(255, 51, 51));
        jButtonExcluirMensagem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExcluirMensagem.setText("Excluir Frase");
        jButtonExcluirMensagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluirMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirMensagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInicGerencia1Layout = new javax.swing.GroupLayout(jPanelInicGerencia1);
        jPanelInicGerencia1.setLayout(jPanelInicGerencia1Layout);
        jPanelInicGerencia1Layout.setHorizontalGroup(
            jPanelInicGerencia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicGerencia1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInicGerencia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonEditarMensage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNovoMensa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExcluirMensagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInicGerencia1Layout.setVerticalGroup(
            jPanelInicGerencia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicGerencia1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonNovoMensa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEditarMensage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExcluirMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/morpheus.png"))); // NOI18N

        javax.swing.GroupLayout jPanelConfigMensagemLayout = new javax.swing.GroupLayout(jPanelConfigMensagem);
        jPanelConfigMensagem.setLayout(jPanelConfigMensagemLayout);
        jPanelConfigMensagemLayout.setHorizontalGroup(
            jPanelConfigMensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConfigMensagemLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelConfigMensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanelConfigMensagemLayout.createSequentialGroup()
                        .addGroup(jPanelConfigMensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelConfigMensagemLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jRadioButtoCodigoFrase)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonFrase)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPesquisarMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabeBotaolPesquisaMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanelConfigMensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelConfigMensagemLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jPanelInicGerencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, Short.MAX_VALUE))
                            .addGroup(jPanelConfigMensagemLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30))
        );
        jPanelConfigMensagemLayout.setVerticalGroup(
            jPanelConfigMensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfigMensagemLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelConfigMensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(jPanelConfigMensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabeBotaolPesquisaMensagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelConfigMensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPesquisarMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtoCodigoFrase)
                            .addComponent(jRadioButtonFrase))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelConfigMensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelInicGerencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jTabbedPaneConfigGeral.addTab("Cadastro de mensagem", jPanelConfigMensagem);

        javax.swing.GroupLayout jPanelTarefasLayout = new javax.swing.GroupLayout(jPanelTarefas);
        jPanelTarefas.setLayout(jPanelTarefasLayout);
        jPanelTarefasLayout.setHorizontalGroup(
            jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPaneConfigGeral)
        );
        jPanelTarefasLayout.setVerticalGroup(
            jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTarefasLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPaneConfigGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 566, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuarioMouseClicked
        // TODO add your handling code here:

     controler.controleEventoTabelaUser();
    }//GEN-LAST:event_jTableUsuarioMouseClicked

    private void EventoNovoUsuario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventoNovoUsuario
controler.novoUsuario();
    }//GEN-LAST:event_EventoNovoUsuario

    private void jPasswordSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordSenhaActionPerformed

    private void jButtonExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirUsuarioActionPerformed
        // TODO add your handling code here:
        controler.DeleTarUsuario();
        
    }//GEN-LAST:event_jButtonExcluirUsuarioActionPerformed

    private void jTableMensagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMensagemMouseClicked
        // TODO add your handling code here:
        controler.controleEventoTabelaMensagem();
    }//GEN-LAST:event_jTableMensagemMouseClicked

    private void jButtonEditarMensageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarMensageActionPerformed
        // TODO add your handling code here:
        controler.AlterarFrase();
    }//GEN-LAST:event_jButtonEditarMensageActionPerformed

    private void jButtonExcluirMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirMensagemActionPerformed
        // TODO add your handling code here:
        controler.DeleTarMensagem();
    }//GEN-LAST:event_jButtonExcluirMensagemActionPerformed

    private void jComboBoxTipoUserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoUserItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxTipoUserItemStateChanged

    private void jTextFieldPesquisarUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarUsuarioKeyReleased
      controler.buscaInformaçoesUsuarios();
    }//GEN-LAST:event_jTextFieldPesquisarUsuarioKeyReleased

    private void jTableMensagemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableMensagemKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableMensagemKeyReleased

    private void jButtonNovoMensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoMensaActionPerformed
        // TODO add your handling code here:
        controler.novamensagem();
    }//GEN-LAST:event_jButtonNovoMensaActionPerformed

    private void jButtonEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarUsuarioActionPerformed
        // TODO add your handling code here:
        controler.AlterarUsuario();
    }//GEN-LAST:event_jButtonEditarUsuarioActionPerformed

    private void BuscaMensagem(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscaMensagem
        // TODO add your handling code here:
        controler.buscaInformaçoesMensagem();
    }//GEN-LAST:event_BuscaMensagem


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCampo;
    private javax.swing.ButtonGroup buttonGroupFrase;
    private javax.swing.ButtonGroup buttonGroupReceberMensagem;
    private javax.swing.JButton jButtonEditarMensage;
    private javax.swing.JButton jButtonEditarUsuario;
    private javax.swing.JButton jButtonExcluirMensagem;
    private javax.swing.JButton jButtonExcluirUsuario;
    private javax.swing.JButton jButtonNovoMensa;
    private javax.swing.JButton jButtonNovoUsuario;
    private javax.swing.JComboBox<String> jComboBoxTipoUser;
    private javax.swing.JLabel jLabeBotaolPesquisaMensagem;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBotaoPesquisar;
    private javax.swing.JLabel jLabelMensagemDia;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelConfigMensagem;
    private javax.swing.JPanel jPanelConfigUsers;
    private javax.swing.JPanel jPanelInicGerencia;
    private javax.swing.JPanel jPanelInicGerencia1;
    private javax.swing.JPanel jPanelTarefas;
    private javax.swing.JPasswordField jPasswordSenha;
    private javax.swing.JRadioButton jRadioButtoCodigoFrase;
    private javax.swing.JRadioButton jRadioButtonBuscaCodigo;
    private javax.swing.JRadioButton jRadioButtonFrase;
    private javax.swing.JRadioButton jRadioButtonNReceMensage;
    private javax.swing.JRadioButton jRadioButtonNome;
    private javax.swing.JRadioButton jRadioButtonReceMensagem;
    private javax.swing.JRadioButton jRadioButtonTipo;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPaneConfigGeral;
    private javax.swing.JTable jTableMensagem;
    private javax.swing.JTable jTableUsuario;
    private javax.swing.JTextArea jTextAreaFrase;
    private javax.swing.JTextField jTextCodiFrase;
    private javax.swing.JTextField jTextCodigouser;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextFieldPesquisarMensagem;
    private javax.swing.JTextField jTextFieldPesquisarUsuario;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextUser;
    // End of variables declaration//GEN-END:variables

    public javax.swing.ButtonGroup getButtonGroupCampo() {
        return buttonGroupCampo;
    }

    public void setButtonGroupCampo(javax.swing.ButtonGroup buttonGroupCampo) {
        this.buttonGroupCampo = buttonGroupCampo;
    }

    public javax.swing.ButtonGroup getButtonGroupFrase() {
        return buttonGroupFrase;
    }

    public void setButtonGroupFrase(javax.swing.ButtonGroup buttonGroupFrase) {
        this.buttonGroupFrase = buttonGroupFrase;
    }

    public javax.swing.ButtonGroup getButtonGroupReceberMensagem() {
        return buttonGroupReceberMensagem;
    }

    public void setButtonGroupReceberMensagem(javax.swing.ButtonGroup buttonGroupReceberMensagem) {
        this.buttonGroupReceberMensagem = buttonGroupReceberMensagem;
    }

    public javax.swing.JButton getjButtonEditarMensage() {
        return jButtonEditarMensage;
    }

    public void setjButtonEditarMensage(javax.swing.JButton jButtonEditarMensage) {
        this.jButtonEditarMensage = jButtonEditarMensage;
    }







    public javax.swing.JButton getjButtonExcluirMensagem() {
        return jButtonExcluirMensagem;
    }

    public void setjButtonExcluirMensagem(javax.swing.JButton jButtonExcluirMensagem) {
        this.jButtonExcluirMensagem = jButtonExcluirMensagem;
    }

    public javax.swing.JButton getjButtonExcluirUsuario() {
        return jButtonExcluirUsuario;
    }

    public void setjButtonExcluirUsuario(javax.swing.JButton jButtonExcluirUsuario) {
        this.jButtonExcluirUsuario = jButtonExcluirUsuario;
    }



    public javax.swing.JComboBox<String> getjComboBoxTipoUser() {
        return jComboBoxTipoUser;
    }

    public void setjComboBoxTipoUser(javax.swing.JComboBox<String> jComboBoxTipoUser) {
        this.jComboBoxTipoUser = jComboBoxTipoUser;
    }

   

    public javax.swing.JPasswordField getjPasswordSenha() {
        return jPasswordSenha;
    }

    public void setjPasswordSenha(javax.swing.JPasswordField jPasswordSenha) {
        this.jPasswordSenha = jPasswordSenha;
    }

    public javax.swing.JRadioButton getjRadioButtonFrase() {
        return jRadioButtonFrase;
    }

    public void setjRadioButtonFrase(javax.swing.JRadioButton jRadioButtonFrase) {
        this.jRadioButtonFrase = jRadioButtonFrase;
    }

    public javax.swing.JRadioButton getjRadioButtonNReceMensage() {
        return jRadioButtonNReceMensage;
    }

    public void setjRadioButtonNReceMensage(javax.swing.JRadioButton jRadioButtonNReceMensage) {
        this.jRadioButtonNReceMensage = jRadioButtonNReceMensage;
    }

    public javax.swing.JRadioButton getjRadioButtonNome() {
        return jRadioButtonNome;
    }

    public void setjRadioButtonNome(javax.swing.JRadioButton jRadioButtonNome) {
        this.jRadioButtonNome = jRadioButtonNome;
    }

    public javax.swing.JRadioButton getjRadioButtonReceMensagem() {
        return jRadioButtonReceMensagem;
    }

    public void setjRadioButtonReceMensagem(javax.swing.JRadioButton jRadioButtonReceMensagem) {
        this.jRadioButtonReceMensagem = jRadioButtonReceMensagem;
    }

    public javax.swing.JRadioButton getjRadioButtonTipo() {
        return jRadioButtonTipo;
    }

    public void setjRadioButtonTipo(javax.swing.JRadioButton jRadioButtonTipo) {
        this.jRadioButtonTipo = jRadioButtonTipo;
    }

    public javax.swing.JTable getjTableMensagem() {
        return jTableMensagem;
    }

    public void setjTableMensagem(javax.swing.JTable jTableMensagem) {
        this.jTableMensagem = jTableMensagem;
    }

    public javax.swing.JTable getjTableUsuario() {
        return jTableUsuario;
    }

    public void setjTableUsuario(javax.swing.JTable jTableUsuario) {
        this.jTableUsuario = jTableUsuario;
    }

    public javax.swing.JTextArea getjTextAreaFrase() {
        return jTextAreaFrase;
    }

    public void setjTextAreaFrase(javax.swing.JTextArea jTextAreaFrase) {
        this.jTextAreaFrase = jTextAreaFrase;
    }

    public javax.swing.JTextField getjTextCodiFrase() {
        return jTextCodiFrase;
    }

    public void setjTextCodiFrase(javax.swing.JTextField jTextCodiFrase) {
        this.jTextCodiFrase = jTextCodiFrase;
    }

    public javax.swing.JTextField getjTextCodigouser() {
        return jTextCodigouser;
    }

    public void setjTextCodigouser(javax.swing.JTextField jTextCodigouser) {
        this.jTextCodigouser = jTextCodigouser;
    }

    public javax.swing.JTextField getjTextEmail() {
        return jTextEmail;
    }

    public void setjTextEmail(javax.swing.JTextField jTextEmail) {
        this.jTextEmail = jTextEmail;
    }

    public javax.swing.JTextField getjTextFieldPesquisarUsuario() {
        return jTextFieldPesquisarUsuario;
    }

    public void setjTextFieldPesquisarUsuario(javax.swing.JTextField jTextFieldPesquisarUsuario) {
        this.jTextFieldPesquisarUsuario = jTextFieldPesquisarUsuario;
    }

    public javax.swing.JTextField getjTextNome() {
        return jTextNome;
    }

    public void setjTextNome(javax.swing.JTextField jTextNome) {
        this.jTextNome = jTextNome;
    }

    public javax.swing.JTextField getjTextUser() {
        return jTextUser;
    }

    public void setjTextUser(javax.swing.JTextField jTextUser) {
        this.jTextUser = jTextUser;
    }

  
    public JButton getjButtonNovoMensa() {
        return jButtonNovoMensa;
    }

    public void setjButtonNovoMensa(JButton jButtonNovoMensa) {
        this.jButtonNovoMensa = jButtonNovoMensa;
    }

  

 

    public JRadioButton getjRadioButtonBuscaCodigo() {
        return jRadioButtonBuscaCodigo;
    }

    public void setjRadioButtonBuscaCodigo(JRadioButton jRadioButtonBuscaCodigo) {
        this.jRadioButtonBuscaCodigo = jRadioButtonBuscaCodigo;
    }
   
 

    private void iniciar() {
      this.controler.carregarListaUsuarios();
      this.controler.carregarListaMensagem();
    }

    public javax.swing.JButton getjButtonEditarUsuario() {
        return jButtonEditarUsuario;
    }

    public void setjButtonEditarUsuario(javax.swing.JButton jButtonEditarUsuario) {
        this.jButtonEditarUsuario = jButtonEditarUsuario;
    }

    public javax.swing.JButton getjButtonNovoUsuario() {
        return jButtonNovoUsuario;
    }

    public void setjButtonNovoUsuario(javax.swing.JButton jButtonNovoUsuario) {
        this.jButtonNovoUsuario = jButtonNovoUsuario;
    }

    public JTextField getjTextFieldPesquisarMensagem() {
        return jTextFieldPesquisarMensagem;
    }

    public void setjTextFieldPesquisarMensagem(JTextField jTextFieldPesquisarMensagem) {
        this.jTextFieldPesquisarMensagem = jTextFieldPesquisarMensagem;
    }

    public JRadioButton getjRadioButtoCodigoFrase() {
        return jRadioButtoCodigoFrase;
    }

    public void setjRadioButtoCodigoFrase(JRadioButton jRadioButtoCodigoFrase) {
        this.jRadioButtoCodigoFrase = jRadioButtoCodigoFrase;
    }
    
}
