/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import controle.ControleTelaRelatorio;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Diana
 */
public class InternoJfTelaRelatorio extends javax.swing.JInternalFrame {

    
    private final ControleTelaRelatorio controle;
    /**
     * Creates new form InternoJfTelaRelatorio
     */
    public InternoJfTelaRelatorio() {
        initComponents();
        controle = new ControleTelaRelatorio(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInicio = new javax.swing.JPanel();
        jPanelDetalhes = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableExercicios = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListTarefa = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListData = new javax.swing.JList<>();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelDetalhes = new javax.swing.JLabel();
        jLabelTarefa = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();

        setBackground(new java.awt.Color(69, 69, 71));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(950, 570));
        setPreferredSize(new java.awt.Dimension(955, 575));

        jPanelInicio.setBackground(new java.awt.Color(69, 69, 71));
        jPanelInicio.setMaximumSize(new java.awt.Dimension(915, 544));

        jPanelDetalhes.setBackground(new java.awt.Color(69, 69, 69));

        jProgressBar1.setForeground(new java.awt.Color(66, 215, 244));
        jProgressBar1.setToolTipText("");
        jProgressBar1.setValue(50);
        jProgressBar1.setStringPainted(true);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Progresso:");

        jSeparator2.setBackground(new java.awt.Color(66, 215, 244));
        jSeparator2.setForeground(new java.awt.Color(66, 215, 244));

        jScrollPane2.setBorder(null);

        jTextArea1.setBackground(new java.awt.Color(69, 69, 69));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(240, 240, 240));
        jTextArea1.setRows(5);
        jTextArea1.setText("Adicione uma observação...");
        jTextArea1.setToolTipText("");
        jScrollPane2.setViewportView(jTextArea1);

        jScrollPane4.setBackground(new java.awt.Color(69, 69, 71));
        jScrollPane4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 69, 71), 1, true));
        jScrollPane4.setViewportBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 69, 71), 1, true));
        jScrollPane4.getViewport().setOpaque(false);

        jTableExercicios.setBackground(new java.awt.Color(69, 69, 71));
        jTableExercicios.setForeground(new java.awt.Color(255, 255, 255));
        jTableExercicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "Exercício 1"},
                {null, "Exercício 2"},
                {null, "Exercício 3"},
                {null, "Exercício 4"},
                {null, "Exercício 5"},
                {null, "Exercício 6"}
            },
            new String [] {
                "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableExercicios.setToolTipText("");
        jTableExercicios.setFocusable(false);
        jTableExercicios.setOpaque(false);
        jTableExercicios.setRowHeight(30);
        jTableExercicios.setSelectionBackground(new java.awt.Color(43, 87, 151));
        jTableExercicios.setShowVerticalLines(false);
        jTableExercicios.getTableHeader().setReorderingAllowed(false);
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) jTableExercicios
        .getDefaultRenderer(JLabel.class);
        renderer.setHorizontalAlignment(SwingConstants.LEFT);
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new java.awt.Color(66,215,244));

        for (int i = 0; i < jTableExercicios.getModel().getColumnCount(); i++) {
            jTableExercicios.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        jTableExercicios.getColumnModel().getColumn(0).setPreferredWidth(6);
        jTableExercicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableExerciciosMouseClicked(evt);
            }
        });
        jTableExercicios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableExerciciosKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTableExercicios);
        if (jTableExercicios.getColumnModel().getColumnCount() > 0) {
            jTableExercicios.getColumnModel().getColumn(0).setMinWidth(20);
            jTableExercicios.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTableExercicios.getColumnModel().getColumn(0).setMaxWidth(20);
        }

        javax.swing.GroupLayout jPanelDetalhesLayout = new javax.swing.GroupLayout(jPanelDetalhes);
        jPanelDetalhes.setLayout(jPanelDetalhesLayout);
        jPanelDetalhesLayout.setHorizontalGroup(
            jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetalhesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDetalhesLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelDetalhesLayout.setVerticalGroup(
            jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetalhesLayout.createSequentialGroup()
                .addGroup(jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
        );

        jScrollPane3.setBorder(null);

        jListTarefa.setBackground(new java.awt.Color(69, 69, 69));
        jListTarefa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jListTarefa.setForeground(new java.awt.Color(255, 255, 255));
        jListTarefa.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "19:00 - Videoconferência", "00:00 - Entrega da Atividade" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListTarefa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListTarefa.setSelectionBackground(new java.awt.Color(43, 87, 151));
        jListTarefa.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListTarefaValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListTarefa);

        jScrollPane1.setBorder(null);
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setOpaque(false);

        jListData.setBackground(new java.awt.Color(69, 69, 69));
        jListData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jListData.setForeground(new java.awt.Color(240, 240, 240));
        jListData.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "15/02/2017", "18/02/2017", "21/02/2017", "24/02/2017" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListData.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListData.setSelectionBackground(new java.awt.Color(43, 87, 151));
        jListData.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jListDataPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jListData);
        jListData.addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()) {
                    try {
                        controle.selecionarTarefasPorData();

                    } catch (SQLException ex) {
                        Logger.getLogger(InternoJfTelaRelatorio.class
                            .getName()).log(Level.SEVERE, null, ex);
                    } catch (NullPointerException eex){
                        System.out.println("Tamanho da jListData: " + jListData.getModel().getSize());
                    }
                }
            }
        });

        jLabelTitulo.setBackground(new java.awt.Color(66, 215, 244));
        jLabelTitulo.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        jLabelTitulo.setText(" Relatório Geral");
        jLabelTitulo.setOpaque(true);

        jLabelDetalhes.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelDetalhes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDetalhes.setText("Detalhes");

        jLabelTarefa.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelTarefa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTarefa.setText("Tarefa");

        jLabelData.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(255, 255, 255));
        jLabelData.setText("Data");

        javax.swing.GroupLayout jPanelInicioLayout = new javax.swing.GroupLayout(jPanelInicio);
        jPanelInicio.setLayout(jPanelInicioLayout);
        jPanelInicioLayout.setHorizontalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelInicioLayout.createSequentialGroup()
                        .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanelInicioLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGap(8, 8, 8)
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInicioLayout.createSequentialGroup()
                        .addComponent(jLabelDetalhes, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                        .addGap(125, 125, 125))
                    .addGroup(jPanelInicioLayout.createSequentialGroup()
                        .addComponent(jPanelDetalhes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelInicioLayout.setVerticalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDetalhes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 951, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jTableExerciciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableExerciciosMouseClicked
        // TODO add your handling code here:

        //        controleEventoTabela();
    }//GEN-LAST:event_jTableExerciciosMouseClicked

    private void jTableExerciciosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableExerciciosKeyReleased
        // TODO add your handling code here:
        //        controleEventoTabela();
    }//GEN-LAST:event_jTableExerciciosKeyReleased

    private void jListTarefaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListTarefaValueChanged
        
    }//GEN-LAST:event_jListTarefaValueChanged

    private void jListDataPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jListDataPropertyChange
        if(jListData.getModel().getSize() > 0){
           
        }
    }//GEN-LAST:event_jListDataPropertyChange




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelDetalhes;
    private javax.swing.JLabel jLabelTarefa;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JList<String> jListData;
    private javax.swing.JList<String> jListTarefa;
    private javax.swing.JPanel jPanelDetalhes;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableExercicios;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    public JList<String> getjListData() {
        return jListData;
    }

    public void setjListData(JList<String> jListData) {
        this.jListData = jListData;
    }

    public JList<String> getjListTarefa() {
        return jListTarefa;
    }

    public void setjListTarefa(JList<String> jListTarefa) {
        this.jListTarefa = jListTarefa;
    }

    
}
