/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import controle.ControlerTelaConfigGeral;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Diana
 */
public class InternoJfTelaConfGeral extends javax.swing.JInternalFrame {

    private final ControlerTelaConfigGeral controler;

    /**
     * Creates new form InternoJfTelaDisicplina
     */
    public InternoJfTelaConfGeral() {
        initComponents();
         controler = new ControlerTelaConfigGeral(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupReceberMensagem = new javax.swing.ButtonGroup();
        buttonGroupCampo = new javax.swing.ButtonGroup();
        buttonGroupFrase = new javax.swing.ButtonGroup();
        jPanelTarefas = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTabbedPaneConfigGeral = new javax.swing.JTabbedPane();
        jPanelConfigUsers = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabelPesquisar = new javax.swing.JLabel();
        jRadioButtonNome = new javax.swing.JRadioButton();
        jRadioButtonTipo = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableUser = new javax.swing.JTable();
        jPanelInicGerencia = new javax.swing.JPanel();
        jButtonEditar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonExcluirAll = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButtonExcluirUser = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextTarefaCod = new javax.swing.JTextField();
        jTextNome = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jTextUser = new javax.swing.JTextField();
        jPasswordSenha1 = new javax.swing.JPasswordField();
        jLabelMensagemDia = new javax.swing.JLabel();
        jRadioButtonConcluido = new javax.swing.JRadioButton();
        jRadioButtonNconcluido = new javax.swing.JRadioButton();
        jTextTarefaCod1 = new javax.swing.JTextField();
        jPanelConfigMensagem = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jRadioButtonFrase = new javax.swing.JRadioButton();
        jRadioButtoIdFrase = new javax.swing.JRadioButton();
        jLabelPesquisar1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextCodiFrase = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaFrase = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableMensagem = new javax.swing.JTable();
        jPanelInicGerencia1 = new javax.swing.JPanel();
        jButtonEditarMensage = new javax.swing.JButton();
        jButtonNovoMensa = new javax.swing.JButton();
        jButtonExcluirAllFrase = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonExcluirMensagem = new javax.swing.JButton();

        setBackground(new java.awt.Color(69, 69, 71));
        setBorder(null);
        setMaximumSize(new java.awt.Dimension(955, 575));
        setPreferredSize(new java.awt.Dimension(955, 575));

        jPanelTarefas.setBackground(new java.awt.Color(69, 69, 71));

        jLabel11.setBackground(new java.awt.Color(153, 180, 51));
        jLabel11.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        jLabel11.setText("Configurações Administrador");
        jLabel11.setMaximumSize(new java.awt.Dimension(318, 45));
        jLabel11.setMinimumSize(new java.awt.Dimension(318, 45));
        jLabel11.setOpaque(true);
        jLabel11.setPreferredSize(new java.awt.Dimension(318, 45));

        jTabbedPaneConfigGeral.setBackground(new java.awt.Color(69, 69, 71));
        jTabbedPaneConfigGeral.setForeground(new java.awt.Color(153, 180, 51));

        jPanelConfigUsers.setBackground(new java.awt.Color(69, 69, 71));

        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 2, true));
        jTextField2.setOpaque(false);

        jLabelPesquisar.setBackground(new java.awt.Color(153, 180, 51));
        jLabelPesquisar.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabelPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPesquisar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPesquisar.setText("Pesquisar ");
        jLabelPesquisar.setOpaque(true);

        buttonGroupCampo.add(jRadioButtonNome);
        jRadioButtonNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonNome.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonNome.setText("Nome");
        jRadioButtonNome.setOpaque(false);

        buttonGroupCampo.add(jRadioButtonTipo);
        jRadioButtonTipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonTipo.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonTipo.setSelected(true);
        jRadioButtonTipo.setText("Tipo");
        jRadioButtonTipo.setOpaque(false);

        jScrollPane4.setBackground(new java.awt.Color(69, 69, 71));
        jScrollPane4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 69, 71), 1, true));
        jScrollPane4.setViewportBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 69, 71), 1, true));
        jScrollPane4.getViewport().setOpaque(false);

        jTableUser.setBackground(new java.awt.Color(69, 69, 71));
        jTableUser.setForeground(new java.awt.Color(255, 255, 255));
        jTableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód", "Nome", "Email", "usuário", "Senha", "Mensagem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUser.setToolTipText("");
        jTableUser.setFocusable(false);
        jTableUser.setOpaque(false);
        jTableUser.setRowHeight(30);
        jTableUser.setSelectionBackground(new java.awt.Color(66, 244, 158));
        jTableUser.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTableUser.setShowVerticalLines(false);
        jTableUser.getTableHeader().setReorderingAllowed(false);
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) jTableUser
        .getDefaultRenderer(JLabel.class);
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new java.awt.Color(153,180,51));
        //60, 74, 178
        //headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < jTableUser.getModel().getColumnCount(); i++) {
            jTableUser.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        jTableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUserMouseClicked(evt);
            }
        });
        jTableUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableUserKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTableUser);

        jPanelInicGerencia.setBackground(new java.awt.Color(69, 69, 71));
        jPanelInicGerencia.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 6, true), "OPÇÕES", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelInicGerencia.setPreferredSize(new java.awt.Dimension(311, 428));

        jButtonEditar.setBackground(new java.awt.Color(181, 92, 28));
        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEditar.setText("EDITAR");
        jButtonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonNovo.setBackground(new java.awt.Color(153, 180, 51));
        jButtonNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNovo.setText("NOVO");
        jButtonNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonExcluirAll.setBackground(new java.awt.Color(255, 0, 0));
        jButtonExcluirAll.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExcluirAll.setText("EXCLUIR TODOS");
        jButtonExcluirAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluirAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirAllActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/morpheus.png"))); // NOI18N

        jButtonExcluirUser.setBackground(new java.awt.Color(255, 51, 51));
        jButtonExcluirUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExcluirUser.setText("Excluir Usuário");
        jButtonExcluirUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluirUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInicGerenciaLayout = new javax.swing.GroupLayout(jPanelInicGerencia);
        jPanelInicGerencia.setLayout(jPanelInicGerenciaLayout);
        jPanelInicGerenciaLayout.setHorizontalGroup(
            jPanelInicGerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicGerenciaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelInicGerenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInicGerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonExcluirAll, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelInicGerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExcluirUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInicGerenciaLayout.setVerticalGroup(
            jPanelInicGerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicGerenciaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExcluirUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jButtonExcluirAll, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(24, 24, 24))
        );

        jPanel2.setBackground(new java.awt.Color(69, 69, 71));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 6, true), "DADOS USUÁRIO", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(570, 529));

        jTextTarefaCod.setEditable(false);
        jTextTarefaCod.setBackground(new java.awt.Color(69, 69, 71));
        jTextTarefaCod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextTarefaCod.setForeground(new java.awt.Color(255, 255, 255));
        jTextTarefaCod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextTarefaCod.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 1, true), "Tipo", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jTextTarefaCod.setMaximumSize(new java.awt.Dimension(385, 40));
        jTextTarefaCod.setPreferredSize(new java.awt.Dimension(385, 40));

        jTextNome.setBackground(new java.awt.Color(69, 69, 71));
        jTextNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextNome.setForeground(new java.awt.Color(255, 255, 255));
        jTextNome.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 1, true), "Nome", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jTextNome.setMaximumSize(new java.awt.Dimension(385, 40));
        jTextNome.setPreferredSize(new java.awt.Dimension(385, 40));

        jTextEmail.setEditable(false);
        jTextEmail.setBackground(new java.awt.Color(69, 69, 71));
        jTextEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextEmail.setForeground(new java.awt.Color(255, 255, 255));
        jTextEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 1, true), "Email", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jTextEmail.setMaximumSize(new java.awt.Dimension(385, 40));
        jTextEmail.setPreferredSize(new java.awt.Dimension(385, 40));

        jTextUser.setEditable(false);
        jTextUser.setBackground(new java.awt.Color(69, 69, 71));
        jTextUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextUser.setForeground(new java.awt.Color(255, 255, 255));
        jTextUser.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 1, true), "Usuário", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jTextUser.setMaximumSize(new java.awt.Dimension(385, 40));
        jTextUser.setPreferredSize(new java.awt.Dimension(385, 40));

        jPasswordSenha1.setEditable(false);
        jPasswordSenha1.setBackground(new java.awt.Color(69, 69, 71));
        jPasswordSenha1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPasswordSenha1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordSenha1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 1, true), "Senha", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPasswordSenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordSenha1ActionPerformed(evt);
            }
        });

        jLabelMensagemDia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelMensagemDia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMensagemDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMensagemDia.setText("Receber mensagem do dia?");

        jRadioButtonConcluido.setBackground(new java.awt.Color(69, 69, 71));
        buttonGroupReceberMensagem.add(jRadioButtonConcluido);
        jRadioButtonConcluido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonConcluido.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonConcluido.setText("Sim");

        jRadioButtonNconcluido.setBackground(new java.awt.Color(69, 69, 71));
        buttonGroupReceberMensagem.add(jRadioButtonNconcluido);
        jRadioButtonNconcluido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonNconcluido.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonNconcluido.setText("Não");

        jTextTarefaCod1.setEditable(false);
        jTextTarefaCod1.setBackground(new java.awt.Color(69, 69, 71));
        jTextTarefaCod1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextTarefaCod1.setForeground(new java.awt.Color(255, 255, 255));
        jTextTarefaCod1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextTarefaCod1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 1, true), "Código", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jTextTarefaCod1.setMaximumSize(new java.awt.Dimension(385, 40));
        jTextTarefaCod1.setPreferredSize(new java.awt.Dimension(385, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelMensagemDia)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonConcluido)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonNconcluido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextTarefaCod1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextTarefaCod, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addComponent(jTextNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextUser, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPasswordSenha1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMensagemDia)
                            .addComponent(jRadioButtonConcluido)
                            .addComponent(jRadioButtonNconcluido)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextTarefaCod, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextTarefaCod1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelConfigUsersLayout = new javax.swing.GroupLayout(jPanelConfigUsers);
        jPanelConfigUsers.setLayout(jPanelConfigUsersLayout);
        jPanelConfigUsersLayout.setHorizontalGroup(
            jPanelConfigUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfigUsersLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jRadioButtonNome)
                .addGap(34, 34, 34)
                .addComponent(jRadioButtonTipo)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelConfigUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConfigUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(jPanelInicGerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanelConfigUsersLayout.setVerticalGroup(
            jPanelConfigUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConfigUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConfigUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addGroup(jPanelConfigUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioButtonNome)
                        .addComponent(jRadioButtonTipo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConfigUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConfigUsersLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelInicGerencia, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        jTabbedPaneConfigGeral.addTab("Gerênciar todos usuários", jPanelConfigUsers);

        jPanelConfigMensagem.setBackground(new java.awt.Color(69, 69, 71));

        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 2, true));
        jTextField3.setOpaque(false);

        buttonGroupFrase.add(jRadioButtonFrase);
        jRadioButtonFrase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonFrase.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonFrase.setSelected(true);
        jRadioButtonFrase.setText("Frase");
        jRadioButtonFrase.setOpaque(false);

        buttonGroupFrase.add(jRadioButtoIdFrase);
        jRadioButtoIdFrase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtoIdFrase.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtoIdFrase.setText("Código");
        jRadioButtoIdFrase.setOpaque(false);

        jLabelPesquisar1.setBackground(new java.awt.Color(153, 180, 51));
        jLabelPesquisar1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabelPesquisar1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPesquisar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPesquisar1.setText("Pesquisar ");
        jLabelPesquisar1.setOpaque(true);

        jPanel3.setBackground(new java.awt.Color(69, 69, 71));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 6, true), "FRASE", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(570, 529));

        jTextCodiFrase.setBackground(new java.awt.Color(69, 69, 71));
        jTextCodiFrase.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jTextCodiFrase.setForeground(new java.awt.Color(255, 255, 255));
        jTextCodiFrase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextCodiFrase.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 1, true), "Código", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jTextCodiFrase.setMaximumSize(new java.awt.Dimension(385, 40));
        jTextCodiFrase.setPreferredSize(new java.awt.Dimension(385, 40));

        jScrollPane6.setBorder(null);

        jTextAreaFrase.setBackground(new java.awt.Color(69, 69, 71));
        jTextAreaFrase.setColumns(20);
        jTextAreaFrase.setRows(5);
        jTextAreaFrase.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 1, true), "Frase", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jScrollPane6.setViewportView(jTextAreaFrase);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextCodiFrase, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextCodiFrase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane5.setBackground(new java.awt.Color(69, 69, 71));
        jScrollPane5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 69, 71), 1, true));
        jScrollPane5.setViewportBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 69, 71), 1, true));
        jScrollPane5.getViewport().setOpaque(false);

        jTableMensagem.setBackground(new java.awt.Color(69, 69, 71));
        jTableMensagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Mensagem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMensagem.setToolTipText("");
        jTableMensagem.setFocusable(false);
        jTableMensagem.setOpaque(false);
        jTableMensagem.setRowHeight(30);
        jTableMensagem.setSelectionBackground(new java.awt.Color(66, 244, 158));
        jTableMensagem.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTableMensagem.setShowVerticalLines(false);
        jTableMensagem.getTableHeader().setReorderingAllowed(false);
        DefaultTableCellRenderer renderere = (DefaultTableCellRenderer) jTableUser
        .getDefaultRenderer(JLabel.class);
        renderere.setHorizontalAlignment(SwingConstants.CENTER);
        DefaultTableCellRenderer headerRenderere = new DefaultTableCellRenderer();
        headerRenderere.setBackground(new java.awt.Color(153,180,51));
        //60, 74, 178
        //headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < jTableMensagem.getModel().getColumnCount(); i++) {
            jTableMensagem.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderere);
        }
        jTableMensagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMensagemMouseClicked(evt);
            }
        });
        jTableMensagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableMensagemKeyReleased(evt);
            }
        });
        jScrollPane5.setViewportView(jTableMensagem);
        if (jTableMensagem.getColumnModel().getColumnCount() > 0) {
            jTableMensagem.getColumnModel().getColumn(0).setMinWidth(30);
            jTableMensagem.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableMensagem.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanelInicGerencia1.setBackground(new java.awt.Color(69, 69, 71));
        jPanelInicGerencia1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 180, 51), 6, true), "OPÇÕES", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelInicGerencia1.setPreferredSize(new java.awt.Dimension(311, 428));

        jButtonEditarMensage.setBackground(new java.awt.Color(181, 92, 28));
        jButtonEditarMensage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEditarMensage.setText("EDITAR");
        jButtonEditarMensage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditarMensage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarMensageActionPerformed(evt);
            }
        });

        jButtonNovoMensa.setBackground(new java.awt.Color(153, 180, 51));
        jButtonNovoMensa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNovoMensa.setText("NOVO");
        jButtonNovoMensa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNovoMensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoMensaActionPerformed(evt);
            }
        });

        jButtonExcluirAllFrase.setBackground(new java.awt.Color(255, 0, 0));
        jButtonExcluirAllFrase.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExcluirAllFrase.setText("EXCLUIR TODOS");
        jButtonExcluirAllFrase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluirAllFrase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirAllFraseActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/morpheus.png"))); // NOI18N

        jButtonExcluirMensagem.setBackground(new java.awt.Color(255, 51, 51));
        jButtonExcluirMensagem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExcluirMensagem.setText("Excluir Frase");
        jButtonExcluirMensagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluirMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirMensagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInicGerencia1Layout = new javax.swing.GroupLayout(jPanelInicGerencia1);
        jPanelInicGerencia1.setLayout(jPanelInicGerencia1Layout);
        jPanelInicGerencia1Layout.setHorizontalGroup(
            jPanelInicGerencia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicGerencia1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelInicGerencia1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInicGerencia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonExcluirAllFrase, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelInicGerencia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonEditarMensage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNovoMensa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExcluirMensagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInicGerencia1Layout.setVerticalGroup(
            jPanelInicGerencia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicGerencia1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButtonNovoMensa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEditarMensage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExcluirMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jButtonExcluirAllFrase, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanelConfigMensagemLayout = new javax.swing.GroupLayout(jPanelConfigMensagem);
        jPanelConfigMensagem.setLayout(jPanelConfigMensagemLayout);
        jPanelConfigMensagemLayout.setHorizontalGroup(
            jPanelConfigMensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfigMensagemLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelConfigMensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                    .addGroup(jPanelConfigMensagemLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jRadioButtoIdFrase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonFrase)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jPanelInicGerencia1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanelConfigMensagemLayout.setVerticalGroup(
            jPanelConfigMensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConfigMensagemLayout.createSequentialGroup()
                .addGroup(jPanelConfigMensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelConfigMensagemLayout.createSequentialGroup()
                        .addContainerGap(38, Short.MAX_VALUE)
                        .addComponent(jPanelInicGerencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelConfigMensagemLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanelConfigMensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtoIdFrase)
                            .addComponent(jRadioButtonFrase))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        jTabbedPaneConfigGeral.addTab("Cadastro de mensagem", jPanelConfigMensagem);

        javax.swing.GroupLayout jPanelTarefasLayout = new javax.swing.GroupLayout(jPanelTarefas);
        jPanelTarefas.setLayout(jPanelTarefasLayout);
        jPanelTarefasLayout.setHorizontalGroup(
            jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPaneConfigGeral)
        );
        jPanelTarefasLayout.setVerticalGroup(
            jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTarefasLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPaneConfigGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 566, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUserMouseClicked
        // TODO add your handling code here:

        //        controleEventoTabela();
    }//GEN-LAST:event_jTableUserMouseClicked

    private void jTableUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableUserKeyReleased
        // TODO add your handling code here:
        //        controleEventoTabela();
    }//GEN-LAST:event_jTableUserKeyReleased

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed

    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonExcluirAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirAllActionPerformed

    private void jPasswordSenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordSenha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordSenha1ActionPerformed

    private void jButtonExcluirUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirUserActionPerformed

    private void jTableMensagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMensagemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableMensagemMouseClicked

    private void jTableMensagemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableMensagemKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableMensagemKeyReleased

    private void jButtonEditarMensageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarMensageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarMensageActionPerformed

    private void jButtonNovoMensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoMensaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovoMensaActionPerformed

    private void jButtonExcluirAllFraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirAllFraseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirAllFraseActionPerformed

    private void jButtonExcluirMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirMensagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirMensagemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCampo;
    private javax.swing.ButtonGroup buttonGroupFrase;
    private javax.swing.ButtonGroup buttonGroupReceberMensagem;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEditarMensage;
    private javax.swing.JButton jButtonExcluirAll;
    private javax.swing.JButton jButtonExcluirAllFrase;
    private javax.swing.JButton jButtonExcluirMensagem;
    private javax.swing.JButton jButtonExcluirUser;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonNovoMensa;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMensagemDia;
    private javax.swing.JLabel jLabelPesquisar;
    private javax.swing.JLabel jLabelPesquisar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelConfigMensagem;
    private javax.swing.JPanel jPanelConfigUsers;
    private javax.swing.JPanel jPanelInicGerencia;
    private javax.swing.JPanel jPanelInicGerencia1;
    private javax.swing.JPanel jPanelTarefas;
    private javax.swing.JPasswordField jPasswordSenha1;
    private javax.swing.JRadioButton jRadioButtoIdFrase;
    private javax.swing.JRadioButton jRadioButtonConcluido;
    private javax.swing.JRadioButton jRadioButtonFrase;
    private javax.swing.JRadioButton jRadioButtonNconcluido;
    private javax.swing.JRadioButton jRadioButtonNome;
    private javax.swing.JRadioButton jRadioButtonTipo;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPaneConfigGeral;
    private javax.swing.JTable jTableMensagem;
    private javax.swing.JTable jTableUser;
    private javax.swing.JTextArea jTextAreaFrase;
    private javax.swing.JTextField jTextCodiFrase;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextTarefaCod;
    private javax.swing.JTextField jTextTarefaCod1;
    private javax.swing.JTextField jTextUser;
    // End of variables declaration//GEN-END:variables
}
