/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import controle.ControleTarefa;
import java.awt.event.ItemEvent;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Diana
 */
public class InternoJfTelaTarefa extends javax.swing.JInternalFrame {

    private final ControleTarefa controle;
    private static boolean editar;
    private TableRowSorter<TableModel> rowSorter;

    /**
     * Creates new form InternoJfTelaDisicplina
     */
    public InternoJfTelaTarefa() {
        initComponents();
        controle = new ControleTarefa(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupStatus = new javax.swing.ButtonGroup();
        buttonGroupDisciplina = new javax.swing.ButtonGroup();
        jPanelTarefas = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLayeredPaneGereTarefa = new javax.swing.JLayeredPane();
        jPanelInicGerencia = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1Descricao = new javax.swing.JTextArea();
        jPanelGerenciatarefa = new javax.swing.JPanel();
        jTextTarefaNome = new javax.swing.JTextField();
        jFormattedTextData = new javax.swing.JFormattedTextField();
        jLabelStatus = new javax.swing.JLabel();
        jRadioButtonConcluido = new javax.swing.JRadioButton();
        jRadioButtonNconcluido = new javax.swing.JRadioButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jButtonSalvar = new javax.swing.JButton();
        jComboBoxDisciplina = new javax.swing.JComboBox<>();
        jFormattedTextHora = new javax.swing.JFormattedTextField();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jPanelTableTarefas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableTarefas = new javax.swing.JTable();
        jPanelEdicaoTarefa = new javax.swing.JPanel();
        jButtonNovaTarefa = new javax.swing.JButton();
        jButtonExcluirTarefa = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jLabelPesquisar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(69, 69, 71));
        setBorder(null);
        setMaximumSize(new java.awt.Dimension(955, 575));
        setPreferredSize(new java.awt.Dimension(955, 575));

        jPanelTarefas.setBackground(new java.awt.Color(69, 69, 71));
        jPanelTarefas.setPreferredSize(new java.awt.Dimension(950, 570));

        jLabel11.setBackground(new java.awt.Color(66, 244, 158));
        jLabel11.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        jLabel11.setText(" Tarefas");
        jLabel11.setMaximumSize(new java.awt.Dimension(318, 45));
        jLabel11.setMinimumSize(new java.awt.Dimension(318, 45));
        jLabel11.setOpaque(true);
        jLabel11.setPreferredSize(new java.awt.Dimension(318, 45));

        jLayeredPaneGereTarefa.setLayout(new java.awt.CardLayout());

        jPanelInicGerencia.setBackground(new java.awt.Color(69, 69, 71));
        jPanelInicGerencia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 244, 158), 2, true));
        jPanelInicGerencia.setPreferredSize(new java.awt.Dimension(311, 428));

        jPanel1.setBackground(new java.awt.Color(69, 69, 71));

        jScrollPane2.setBorder(null);

        jTextArea1Descricao.setEditable(false);
        jTextArea1Descricao.setBackground(new java.awt.Color(69, 69, 69));
        jTextArea1Descricao.setColumns(20);
        jTextArea1Descricao.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextArea1Descricao.setForeground(new java.awt.Color(240, 240, 240));
        jTextArea1Descricao.setLineWrap(true);
        jTextArea1Descricao.setRows(5);
        jTextArea1Descricao.setToolTipText("");
        jTextArea1Descricao.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 244, 158)), "Descrição da Tarefa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Candara", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jTextArea1Descricao.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTextArea1Descricao);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanelInicGerenciaLayout = new javax.swing.GroupLayout(jPanelInicGerencia);
        jPanelInicGerencia.setLayout(jPanelInicGerenciaLayout);
        jPanelInicGerenciaLayout.setHorizontalGroup(
            jPanelInicGerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicGerenciaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInicGerenciaLayout.setVerticalGroup(
            jPanelInicGerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicGerenciaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLayeredPaneGereTarefa.add(jPanelInicGerencia, "card2");

        jPanelGerenciatarefa.setBackground(new java.awt.Color(69, 69, 71));
        jPanelGerenciatarefa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 244, 158), 2, true));

        jTextTarefaNome.setBackground(new java.awt.Color(69, 69, 71));
        jTextTarefaNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextTarefaNome.setForeground(new java.awt.Color(255, 255, 255));
        jTextTarefaNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextTarefaNome.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 215, 244), 1, true), "Nome", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jTextTarefaNome.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextTarefaNome.setMaximumSize(new java.awt.Dimension(385, 40));
        jTextTarefaNome.setPreferredSize(new java.awt.Dimension(385, 40));

        jFormattedTextData.setBackground(new java.awt.Color(69, 69, 71));
        jFormattedTextData.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 215, 244), 1, true), "Data", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jFormattedTextData.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedTextData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextData.setCaretColor(new java.awt.Color(255, 255, 255));
        jFormattedTextData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jFormattedTextData.setSelectedTextColor(new java.awt.Color(51, 153, 255));

        jLabelStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStatus.setText("Status");

        jRadioButtonConcluido.setBackground(new java.awt.Color(69, 69, 71));
        buttonGroupStatus.add(jRadioButtonConcluido);
        jRadioButtonConcluido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButtonConcluido.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonConcluido.setText("Concluido");

        jRadioButtonNconcluido.setBackground(new java.awt.Color(69, 69, 71));
        buttonGroupStatus.add(jRadioButtonNconcluido);
        jRadioButtonNconcluido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButtonNconcluido.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonNconcluido.setSelected(true);
        jRadioButtonNconcluido.setText("Não Concluído");

        jScrollPane5.setBorder(null);

        jTextAreaDescricao.setBackground(new java.awt.Color(69, 69, 71));
        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextAreaDescricao.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaDescricao.setLineWrap(true);
        jTextAreaDescricao.setRows(5);
        jTextAreaDescricao.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 215, 244), 1, true), "Descrição", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jTextAreaDescricao.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextAreaDescricao.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane5.setViewportView(jTextAreaDescricao);

        jButtonSalvar.setBackground(new java.awt.Color(181, 92, 28));
        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSalvar.setText("SALVAR");
        jButtonSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jComboBoxDisciplina.setBackground(new java.awt.Color(69, 69, 69));
        jComboBoxDisciplina.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jComboBoxDisciplina.setForeground(new java.awt.Color(240, 240, 240));
        jComboBoxDisciplina.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 215, 244)), "Disciplina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jComboBoxDisciplina.setFocusable(false);
        jComboBoxDisciplina.setOpaque(false);
        jComboBoxDisciplina.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDisciplinaItemStateChanged(evt);
            }
        });

        jFormattedTextHora.setBackground(new java.awt.Color(69, 69, 71));
        jFormattedTextHora.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 215, 244), 1, true), "Hora", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jFormattedTextHora.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedTextHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextHora.setCaretColor(new java.awt.Color(255, 255, 255));
        jFormattedTextHora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jFormattedTextHora.setSelectedTextColor(new java.awt.Color(51, 153, 255));

        jButtonCancelar.setBackground(new java.awt.Color(181, 92, 28));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGerenciatarefaLayout = new javax.swing.GroupLayout(jPanelGerenciatarefa);
        jPanelGerenciatarefa.setLayout(jPanelGerenciatarefaLayout);
        jPanelGerenciatarefaLayout.setHorizontalGroup(
            jPanelGerenciatarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGerenciatarefaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jFormattedTextData, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFormattedTextHora, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanelGerenciatarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxDisciplina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGerenciatarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGerenciatarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextTarefaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addContainerGap())
            .addGroup(jPanelGerenciatarefaLayout.createSequentialGroup()
                .addGroup(jPanelGerenciatarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGerenciatarefaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabelStatus)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonConcluido))
                    .addGroup(jPanelGerenciatarefaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelGerenciatarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonNconcluido))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanelGerenciatarefaLayout.setVerticalGroup(
            jPanelGerenciatarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGerenciatarefaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTextTarefaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGerenciatarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextData, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextHora, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGerenciatarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus)
                    .addComponent(jRadioButtonConcluido)
                    .addComponent(jRadioButtonNconcluido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGerenciatarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLayeredPaneGereTarefa.add(jPanelGerenciatarefa, "card3");

        jTextFieldPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPesquisar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 244, 158), 2, true));
        //código para adicionar um document listener ao campo de pesquisa
        jTextFieldPesquisar.getDocument().addDocumentListener(new DocumentListener(){
            public void insertUpdate(DocumentEvent evt) {
                jTextFieldPesquisarInserir(evt);
            }

            public void removeUpdate(DocumentEvent evt) {
                jTextFieldPesquisarRemover(evt);
            }

            public void changedUpdate(DocumentEvent evt) {
                throw new UnsupportedOperationException("Not supported yet.");
                //To change body of generated methods, choose Tools | Templates.
            }
        });
        jTextFieldPesquisar.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextFieldPesquisar.setOpaque(false);
        jTextFieldPesquisar.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jTextFieldPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldPesquisarMouseClicked(evt);
            }
        });
        jTextFieldPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarActionPerformed(evt);
            }
        });

        jPanelTableTarefas.setBackground(new java.awt.Color(69, 69, 71));
        jPanelTableTarefas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 69, 71), 6, true));
        jPanelTableTarefas.setOpaque(false);

        jScrollPane4.setBackground(new java.awt.Color(69, 69, 71));
        jScrollPane4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 69, 71), 1, true));
        jScrollPane4.setViewportBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 69, 71), 1, true));
        jScrollPane4.getViewport().setOpaque(false);

        jTableTarefas.setBackground(new java.awt.Color(69, 69, 71));
        jTableTarefas.setForeground(new java.awt.Color(255, 255, 255));
        jTableTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), null, "05/05/2019", null, "Matematica", "dasdas", null, null},
                { new Integer(2), null, "05/06/2019", null, "Portugues", "sdasdas", null, null},
                { new Integer(3), null, "05/07/2019", null, "Sistemas Operacionais", "dasdsad", null, null},
                { new Integer(4), null, "05/08/2019", null, "Programação I", "asdasd",  new Boolean(true), null},
                { new Integer(5), null, "05/09/2019", null, "Modelos de Gestão", "asdasd",  new Boolean(true), null},
                { new Integer(6), null, "05/10/2019", null, "Matematica", "sdasd", null, null},
                { new Integer(7), null, "05/11/2019", null, "Sistemas Operacionais", "asdsadsa", null, null}
            },
            new String [] {
                "Id", "Nome", "Data", "Hora", "Disciplina", "Descrição", "Concluído", "Id Disciplina"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTarefas.setToolTipText("");
        jTableTarefas.setFocusable(false);
        jTableTarefas.setOpaque(false);
        jTableTarefas.setRowHeight(30);
        jTableTarefas.setSelectionBackground(new java.awt.Color(66, 244, 158));
        jTableTarefas.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTableTarefas.setShowVerticalLines(false);
        jTableTarefas.getTableHeader().setReorderingAllowed(false);
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) jTableTarefas
        .getDefaultRenderer(JLabel.class);
        renderer.setHorizontalAlignment(SwingConstants.LEFT);
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setHorizontalAlignment(SwingConstants.LEFT);
        headerRenderer.setBackground(new java.awt.Color(40, 109, 58));
        //60, 74, 178
        //headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < jTableTarefas.getModel().getColumnCount(); i++) {
            jTableTarefas.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }

        jTableTarefas.getModel().addTableModelListener(new TableModelListener(){
            public void tableChanged(TableModelEvent evt) {
                jTableTarefasTableChanged(evt);
            }
        });

        jTableTarefas.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent evt) {
                jTableTarefasSelectionMade(evt);
            }
        });

        //Row sorter para permitir a busca dinâmica na jTable
        rowSorter = new TableRowSorter<>(jTableTarefas.getModel());
        jTableTarefas.setRowSorter(rowSorter);
        jTableTarefas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTarefasMouseClicked(evt);
            }
        });
        jTableTarefas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableTarefasKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTableTarefas);
        if (jTableTarefas.getColumnModel().getColumnCount() > 0) {
            jTableTarefas.getColumnModel().getColumn(0).setMinWidth(0);
            jTableTarefas.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTableTarefas.getColumnModel().getColumn(0).setMaxWidth(0);
            jTableTarefas.getColumnModel().getColumn(2).setMinWidth(80);
            jTableTarefas.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTableTarefas.getColumnModel().getColumn(2).setMaxWidth(80);
            jTableTarefas.getColumnModel().getColumn(3).setMinWidth(0);
            jTableTarefas.getColumnModel().getColumn(3).setPreferredWidth(0);
            jTableTarefas.getColumnModel().getColumn(3).setMaxWidth(0);
            jTableTarefas.getColumnModel().getColumn(5).setMinWidth(0);
            jTableTarefas.getColumnModel().getColumn(5).setPreferredWidth(0);
            jTableTarefas.getColumnModel().getColumn(5).setMaxWidth(0);
            jTableTarefas.getColumnModel().getColumn(6).setMinWidth(70);
            jTableTarefas.getColumnModel().getColumn(6).setPreferredWidth(70);
            jTableTarefas.getColumnModel().getColumn(6).setMaxWidth(70);
            jTableTarefas.getColumnModel().getColumn(7).setMinWidth(0);
            jTableTarefas.getColumnModel().getColumn(7).setPreferredWidth(0);
            jTableTarefas.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanelTableTarefasLayout = new javax.swing.GroupLayout(jPanelTableTarefas);
        jPanelTableTarefas.setLayout(jPanelTableTarefasLayout);
        jPanelTableTarefasLayout.setHorizontalGroup(
            jPanelTableTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableTarefasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelTableTarefasLayout.setVerticalGroup(
            jPanelTableTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableTarefasLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 107, Short.MAX_VALUE))
        );

        jPanelEdicaoTarefa.setBackground(new java.awt.Color(69, 69, 71));
        jPanelEdicaoTarefa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 244, 158), 2, true));

        jButtonNovaTarefa.setBackground(new java.awt.Color(66, 244, 158));
        jButtonNovaTarefa.setText("Nova Tarefa");
        jButtonNovaTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaTarefaActionPerformed(evt);
            }
        });

        jButtonExcluirTarefa.setBackground(new java.awt.Color(66, 244, 158));
        jButtonExcluirTarefa.setText("Excluir Tarefa");
        jButtonExcluirTarefa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonExcluirTarefaMouseClicked(evt);
            }
        });
        jButtonExcluirTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirTarefaActionPerformed(evt);
            }
        });

        jButtonEditar.setBackground(new java.awt.Color(66, 244, 158));
        jButtonEditar.setText("Editar Tarefa");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEdicaoTarefaLayout = new javax.swing.GroupLayout(jPanelEdicaoTarefa);
        jPanelEdicaoTarefa.setLayout(jPanelEdicaoTarefaLayout);
        jPanelEdicaoTarefaLayout.setHorizontalGroup(
            jPanelEdicaoTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEdicaoTarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNovaTarefa)
                .addGap(5, 5, 5)
                .addComponent(jButtonEditar)
                .addGap(5, 5, 5)
                .addComponent(jButtonExcluirTarefa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEdicaoTarefaLayout.setVerticalGroup(
            jPanelEdicaoTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEdicaoTarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEdicaoTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonExcluirTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNovaTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabelPesquisar.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabelPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPesquisar.setText("Pesquisar Tarefas:");

        javax.swing.GroupLayout jPanelTarefasLayout = new javax.swing.GroupLayout(jPanelTarefas);
        jPanelTarefas.setLayout(jPanelTarefasLayout);
        jPanelTarefasLayout.setHorizontalGroup(
            jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelTarefasLayout.createSequentialGroup()
                .addGroup(jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelTarefasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelTableTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelTarefasLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabelPesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPaneGereTarefa)
                    .addComponent(jPanelEdicaoTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanelTarefasLayout.setVerticalGroup(
            jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTarefasLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelTarefasLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanelEdicaoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPaneGereTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelTarefasLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPesquisar))
                        .addGap(23, 23, 23)
                        .addComponent(jPanelTableTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelTarefas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableTarefasTableChanged(TableModelEvent evt) {
        if (evt.getType() == TableModelEvent.UPDATE) {
            int idTarefa = (int) jTableTarefas.getValueAt(jTableTarefas.getSelectedRow(), 0);
            boolean status = (boolean) jTableTarefas.getValueAt(jTableTarefas.getSelectedRow(), jTableTarefas.getSelectedColumn());
            System.out.println("Id da Tarefa: " + idTarefa);
            System.out.println("Linha selecionada: " + status);
            try {
                controle.editarStatusTarefa(idTarefa, status);
            } catch (ParseException ex) {
                Logger.getLogger(InternoJfTelaTarefa.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    private void jTableTarefasSelectionMade(ListSelectionEvent evt) {
        try {
            if (jTableTarefas.getModel().getRowCount() > 0) {
                jTextArea1Descricao.setText((String) jTableTarefas.getValueAt(jTableTarefas.getSelectedRow(), 5));
            } else {
                jTextAreaDescricao.setText("");
            }
        } catch (IndexOutOfBoundsException ex) {
        }
    }

    ;

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        editar = true;
        if (jTableTarefas.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Nenhuma tarefa foi selecionada");
        } else {
            try {
                controle.TrocaTarefas(jPanelGerenciatarefa);
                controle.carregarCamposTarefa();
            } catch (ParseException ex) {
                Logger.getLogger(InternoJfTelaTarefa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirTarefaActionPerformed
        if (jTableTarefas.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Nenhuma tarefa foi selecionada");
        } else {
            try {
                controle.removerTarefa();
            } catch (ParseException ex) {
                Logger.getLogger(InternoJfTelaTarefa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonExcluirTarefaActionPerformed

    private void jButtonNovaTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaTarefaActionPerformed
        editar = false;
        controle.TrocaTarefas(jPanelGerenciatarefa);
        controle.exibirTodasDisciplinas(0);

    }//GEN-LAST:event_jButtonNovaTarefaActionPerformed

    private void jTableTarefasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableTarefasKeyReleased
        // TODO add your handling code here:
        //        controleEventoTabela();
    }//GEN-LAST:event_jTableTarefasKeyReleased

    private void jTableTarefasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTarefasMouseClicked
        // TODO add your handling code here:

        //        controleEventoTabela();
    }//GEN-LAST:event_jTableTarefasMouseClicked

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (editar) {
            try {
                if (controle.editarTarefa()) {
                    controle.TrocaTarefas(jPanelInicGerencia);
                }
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Digite uma data válida.");
            }
        } else {
            try {
                if (controle.salvarTarefa()) {
                    controle.TrocaTarefas(jPanelInicGerencia);
                }
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Digite uma data válida.");
            }
        }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirTarefaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExcluirTarefaMouseClicked

    }//GEN-LAST:event_jButtonExcluirTarefaMouseClicked

    private void jComboBoxDisciplinaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDisciplinaItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {

        }
    }//GEN-LAST:event_jComboBoxDisciplinaItemStateChanged

    private void jTextFieldPesquisarInserir(DocumentEvent evt) {
        String texto = jTextFieldPesquisar.getText();
        try {
            if (texto.trim().length() == 0) {
                rowSorter.setRowFilter(null);
            } else {
                rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto));
            }
        } catch (IndexOutOfBoundsException ex) {
            System.out.println("Erro");
        }
    }

    private void jTextFieldPesquisarRemover(DocumentEvent evt) {
        String texto = jTextFieldPesquisar.getText();
        try {
            if (texto.trim().length() == 0) {
                rowSorter.setRowFilter(null);
            } else {
                rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto));
            }
        } catch (IndexOutOfBoundsException ex) {
            System.out.println("Erro");
        }
    }

    private void jTextFieldPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarActionPerformed
        // TODO add your handling code here:String texto = jTextFieldPesquisar.getText();


    }//GEN-LAST:event_jTextFieldPesquisarActionPerformed

    private void jTextFieldPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarMouseClicked
        jTableTarefas.getSelectionModel().clearSelection();
    }//GEN-LAST:event_jTextFieldPesquisarMouseClicked

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed

        controle.TrocaTarefas(jPanelInicGerencia);
        controle.limparCampos();
    }//GEN-LAST:event_jButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDisciplina;
    private javax.swing.ButtonGroup buttonGroupStatus;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluirTarefa;
    private javax.swing.JButton jButtonNovaTarefa;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxDisciplina;
    private javax.swing.JFormattedTextField jFormattedTextData;
    private javax.swing.JFormattedTextField jFormattedTextHora;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabelPesquisar;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLayeredPane jLayeredPaneGereTarefa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelEdicaoTarefa;
    private javax.swing.JPanel jPanelGerenciatarefa;
    private javax.swing.JPanel jPanelInicGerencia;
    private javax.swing.JPanel jPanelTableTarefas;
    private javax.swing.JPanel jPanelTarefas;
    private javax.swing.JRadioButton jRadioButtonConcluido;
    private javax.swing.JRadioButton jRadioButtonNconcluido;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableTarefas;
    private javax.swing.JTextArea jTextArea1Descricao;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextTarefaNome;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLayeredPane getjLayeredPaneGereTarefa() {
        return jLayeredPaneGereTarefa;
    }

    public void setjLayeredPaneGereTarefa(javax.swing.JLayeredPane jLayeredPaneGereTarefa) {
        this.jLayeredPaneGereTarefa = jLayeredPaneGereTarefa;
    }

    public JTable getjTableTarefas() {
        return jTableTarefas;
    }

    public JComboBox<String> getjComboBoxDisciplina() {
        return jComboBoxDisciplina;
    }

    public void setjComboBoxDisciplina(JComboBox<String> jComboBoxDisciplina) {
        this.jComboBoxDisciplina = jComboBoxDisciplina;
    }

    public JFormattedTextField getjFormattedTextData() {
        return jFormattedTextData;
    }

    public void setjFormattedTextData(JFormattedTextField jFormattedTextData) {
        this.jFormattedTextData = jFormattedTextData;
    }

    public JFormattedTextField getjFormattedTextHora() {
        return jFormattedTextHora;
    }

    public void setjFormattedTextHora(JFormattedTextField jFormattedTextHora) {
        this.jFormattedTextHora = jFormattedTextHora;
    }

    public JTextArea getjTextAreaDescricao() {
        return jTextAreaDescricao;
    }

    public void setjTextAreaDescricao(JTextArea jTextAreaDescricao) {
        this.jTextAreaDescricao = jTextAreaDescricao;
    }

    public JTextField getjTextTarefaNome() {
        return jTextTarefaNome;
    }

    public void setjTextTarefaNome(JTextField jTextTarefaNome) {
        this.jTextTarefaNome = jTextTarefaNome;
    }

    public JRadioButton getjRadioButtonConcluido() {
        return jRadioButtonConcluido;
    }

    public void setjRadioButtonConcluido(JRadioButton jRadioButtonConcluido) {
        this.jRadioButtonConcluido = jRadioButtonConcluido;
    }

}
