/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.border.LineBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Diana
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setResizable(false);
    setLocationRelativeTo(null);
 //pegarResolucao();     
 
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelAluno = new javax.swing.JLabel();
        jLabelTela1 = new javax.swing.JLabel();
        jLabelTela2 = new javax.swing.JLabel();
        jLabelMorp = new javax.swing.JLabel();
        jLabelTela3 = new javax.swing.JLabel();
        jLabelTela4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelsair = new javax.swing.JLabel();
        jLabelMini = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/recursos/Morpheus_Labs_Logo_2.png"));
        Image image = icon.getImage();
        jDesktopPanePrincipal = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(69, 69, 69));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(69, 69, 71));
        jPanel1.setFocusTraversalPolicyProvider(true);

        jLabelAluno.setBackground(new java.awt.Color(66, 215, 244));
        jLabelAluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/estudante.png"))); // NOI18N
        jLabelAluno.setOpaque(true);

        jLabelTela1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTela1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTela1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTela1.setText("1");
        jLabelTela1.setToolTipText("Home");
        jLabelTela1.setPreferredSize(new java.awt.Dimension(64, 64));
        jLabelTela1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTela1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTela1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTela1MouseExited(evt);
            }
        });

        jLabelTela2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTela2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTela2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTela2.setText("2");
        jLabelTela2.setToolTipText("Home");
        jLabelTela2.setPreferredSize(new java.awt.Dimension(64, 64));
        jLabelTela2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTela2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTela2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTela2MouseExited(evt);
            }
        });

        jLabelMorp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMorp.setText("Logo aqui");
        jLabelMorp.setToolTipText("");

        jLabelTela3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTela3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTela3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTela3.setText("3");
        jLabelTela3.setToolTipText("Home");
        jLabelTela3.setPreferredSize(new java.awt.Dimension(64, 64));
        jLabelTela3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTela3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTela3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTela3MouseExited(evt);
            }
        });

        jLabelTela4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTela4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTela4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTela4.setText("4");
        jLabelTela4.setToolTipText("Home");
        jLabelTela4.setPreferredSize(new java.awt.Dimension(64, 64));
        jLabelTela4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTela4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTela4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMorp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTela4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTela3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTela1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTela2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTela1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTela2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTela3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTela4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMorp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(69, 69, 69));

        jLabelsair.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelsair.setForeground(new java.awt.Color(181, 92, 28));
        jLabelsair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelsair.setText("X");
        jLabelsair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelsairMouseClicked(evt);
            }
        });

        jLabelMini.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelMini.setForeground(new java.awt.Color(181, 92, 28));
        jLabelMini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMini.setText("-");
        jLabelMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMiniMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Candara", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(66, 215, 244));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Morpheus Study");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMini, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelsair, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelsair)
                        .addComponent(jLabelMini, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jDesktopPanePrincipal.setBackground(new java.awt.Color(69, 69, 69));

        jLabel5.setBackground(new java.awt.Color(66, 215, 244));
        jLabel5.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        jLabel5.setText("Relatório Geral");
        jLabel5.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data");

        jLabel4.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tarefa");

        jLabel1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Detalhes");

        jScrollPane1.setBorder(null);
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setOpaque(false);

        jList1.setBackground(new java.awt.Color(69, 69, 69));
        jList1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(240, 240, 240));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "15/02/2017", "18/02/2017", "21/02/2017", "24/02/2017" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setSelectionBackground(new java.awt.Color(66, 215, 244));
        jScrollPane1.setViewportView(jList1);

        jScrollPane3.setBorder(null);

        jList2.setBackground(new java.awt.Color(69, 69, 69));
        jList2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jList2.setForeground(new java.awt.Color(240, 240, 240));
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "19:00 - Videoconferência", "00:00 - Entrega da Atividade" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList2.setSelectionBackground(new java.awt.Color(66, 215, 244));
        jScrollPane3.setViewportView(jList2);

        jPanel3.setBackground(new java.awt.Color(69, 69, 69));

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBox1.setText("Exercício 1");
        jCheckBox1.setOpaque(false);

        jProgressBar1.setForeground(new java.awt.Color(66, 215, 244));
        jProgressBar1.setToolTipText("");
        jProgressBar1.setValue(50);
        jProgressBar1.setStringPainted(true);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Progresso:");

        jSeparator1.setBackground(new java.awt.Color(66, 215, 244));
        jSeparator1.setForeground(new java.awt.Color(66, 215, 244));

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBox2.setText("Exercício 2");
        jCheckBox2.setOpaque(false);

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBox3.setText("Exercício 3");
        jCheckBox3.setOpaque(false);

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBox4.setText("Exercício 4");
        jCheckBox4.setOpaque(false);
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBox5.setText("Exercício 5");
        jCheckBox5.setOpaque(false);

        jCheckBox6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBox6.setText("Exercício 6");
        jCheckBox6.setOpaque(false);

        jSeparator2.setBackground(new java.awt.Color(66, 215, 244));
        jSeparator2.setForeground(new java.awt.Color(66, 215, 244));

        jScrollPane2.setBorder(null);

        jTextArea1.setBackground(new java.awt.Color(69, 69, 69));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(240, 240, 240));
        jTextArea1.setRows(5);
        jTextArea1.setText("Adicione uma observação...");
        jTextArea1.setToolTipText("");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
        );

        jDesktopPanePrincipal.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePrincipal.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePrincipal.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePrincipal.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePrincipal.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePrincipal.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPanePrincipalLayout = new javax.swing.GroupLayout(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setLayout(jDesktopPanePrincipalLayout);
        jDesktopPanePrincipalLayout.setHorizontalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPanePrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPanePrincipalLayout.setVerticalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPanePrincipalLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPanePrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jDesktopPanePrincipalLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDesktopPanePrincipal)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDesktopPanePrincipal))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        //testar se é a primeira vez do usuário
        contadorLogin();
    }//GEN-LAST:event_formWindowOpened

    private void jLabelMiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMiniMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMiniMouseClicked

    private void jLabelsairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelsairMouseClicked

    private void jLabelTela1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTela1MouseExited
        // TODO add your handling code here:
         jLabelTela1.setBackground(new Color(69, 69, 71));
 jLabelTela1.setBorder(new LineBorder(new Color(69, 69, 71),2,true));
    }//GEN-LAST:event_jLabelTela1MouseExited

    private void jLabelTela1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTela1MouseEntered
        // TODO add your handling code here:
         jLabelTela1.setOpaque(true);
 jLabelTela1.setBackground(new Color(66, 215, 244));
 jLabelTela1.setBorder(new LineBorder(new Color(66, 215, 244),2,true));
    }//GEN-LAST:event_jLabelTela1MouseEntered

    private void jLabelTela2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTela2MouseEntered
        // TODO add your handling code here:
        jLabelTela2.setOpaque(true);
 jLabelTela2.setBackground(new Color(66, 215, 244));
 jLabelTela2.setBorder(new LineBorder(new Color(66, 215, 244),2,true));
    }//GEN-LAST:event_jLabelTela2MouseEntered

    private void jLabelTela2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTela2MouseExited
        // TODO add your handling code here:
          jLabelTela2.setBackground(new Color(69, 69, 71));
 jLabelTela2.setBorder(new LineBorder(new Color(69, 69, 71),2,true));
    }//GEN-LAST:event_jLabelTela2MouseExited

    private void jLabelTela1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTela1MouseClicked
        // TODO add your handling code here:
        Home home =new Home();
        jDesktopPanePrincipal.add(home);
        home.setBounds(0, 0, jDesktopPanePrincipal.getWidth(), jDesktopPanePrincipal.getHeight());
      //  home.setBorder(null);//retirar bordas
        ((BasicInternalFrameUI)home.getUI()).setNorthPane(null);
        home.show();
    //    home.dispose();
        
    }//GEN-LAST:event_jLabelTela1MouseClicked

    private void jLabelTela3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTela3MouseEntered
        // TODO add your handling code here:
        jLabelTela3.setOpaque(true);
 jLabelTela3.setBackground(new Color(66, 215, 244));
 jLabelTela3.setBorder(new LineBorder(new Color(66, 215, 244),2,true));
        
    }//GEN-LAST:event_jLabelTela3MouseEntered

    private void jLabelTela3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTela3MouseExited
        // TODO add your handling code here:
            jLabelTela3.setBackground(new Color(69, 69, 71));
 jLabelTela3.setBorder(new LineBorder(new Color(69, 69, 71),2,true));
    }//GEN-LAST:event_jLabelTela3MouseExited

    private void jLabelTela4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTela4MouseEntered
        // TODO add your handling code here:
        jLabelTela4.setOpaque(true);
 jLabelTela4.setBackground(new Color(66, 215, 244));
 jLabelTela4.setBorder(new LineBorder(new Color(66, 215, 244),2,true));
    }//GEN-LAST:event_jLabelTela4MouseEntered

    private void jLabelTela4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTela4MouseExited
        // TODO add your handling code here:
          jLabelTela4.setBackground(new Color(69, 69, 71));
 jLabelTela4.setBorder(new LineBorder(new Color(69, 69, 71),2,true));
    }//GEN-LAST:event_jLabelTela4MouseExited

    private void jLabelTela2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTela2MouseClicked
        // TODO add your handling code here:
         CadastroCurso curso =new CadastroCurso();
        jDesktopPanePrincipal.add(curso);
        curso.setBounds(0, 0, jDesktopPanePrincipal.getWidth(), jDesktopPanePrincipal.getHeight());
    //    curso.setBorder(null);//retirar bordas
        ((BasicInternalFrameUI)curso.getUI()).setNorthPane(null);
        curso.show();
    }//GEN-LAST:event_jLabelTela2MouseClicked

    private void jLabelTela3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTela3MouseClicked
        // TODO add your handling code here:
            TelaConfiguracao tela3 =new TelaConfiguracao();
        jDesktopPanePrincipal.add(tela3);
        tela3.setBounds(0, 0, jDesktopPanePrincipal.getWidth(), jDesktopPanePrincipal.getHeight());
      //  home.setBorder(null);//retirar bordas
        ((BasicInternalFrameUI)tela3.getUI()).setNorthPane(null);
        tela3.show();
    }//GEN-LAST:event_jLabelTela3MouseClicked

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    private void pegarResolucao() {
      Toolkit t = Toolkit.getDefaultToolkit();
        Dimension dimensao = t.getScreenSize();
      //  System.out.println(t);
        this.setSize((dimensao.width - 410 ), (dimensao.height - 130));
    }
    ////Metodo mostrar a tela de boas vinda
public void contadorLogin(){
    int contLog = 0;
    if(contLog==0){
        boaVinda boavinda  = new boaVinda(this, true);
        boavinda.setVisible(true);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JDesktopPane jDesktopPanePrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAluno;
    private javax.swing.JLabel jLabelMini;
    private javax.swing.JLabel jLabelMorp;
    private javax.swing.JLabel jLabelTela1;
    private javax.swing.JLabel jLabelTela2;
    private javax.swing.JLabel jLabelTela3;
    private javax.swing.JLabel jLabelTela4;
    private javax.swing.JLabel jLabelsair;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
