INSERT INTO curso(nome, idusuario) VALUES ('Análise e Desenvolvimento de Sistemas', 1);

INSERT INTO 
disciplina(nome, datainicio, datatermino, domingo, segunda, terca, quarta, quinta, sexta, sabado, idcurso) 
VALUES 	('Introdução à Computação', '2018-02-20', '2018-05-06', false, false, false, true, false, false, false, 
			(SELECT curso.idcurso FROM curso WHERE curso.nome = 'Análise e Desenvolvimento de Sistemas')),
		('Leitura e Produção de Textos', '2018-02-20', '2018-05-06', false, true, false, false, false, false, false, 
			(SELECT curso.idcurso FROM curso WHERE curso.nome = 'Análise e Desenvolvimento de Sistemas')),
		('Projeto Integrador I - Aperfeiçoamento da Lógica e Escrita', '2018-02-20', '2018-05-06', false, false, false, false, false, true, false, 
			(SELECT curso.idcurso FROM curso WHERE curso.nome = 'Análise e Desenvolvimento de Sistemas')),
		('Análise e Modelagem de Dados', '2018-05-08', '2018-07-15', false, false, true, false, false, false, false, 
			(SELECT curso.idcurso FROM curso WHERE curso.nome = 'Análise e Desenvolvimento de Sistemas')),
		('Matemática e Estatística Aplicada', '2018-05-08', '2018-07-15', false, false, false, false, true, false, false, 
			(SELECT curso.idcurso FROM curso WHERE curso.nome = 'Análise e Desenvolvimento de Sistemas')),
		('Projeto Integrador II - Raciocínio Lógico e Matemático', '2018-05-08', '2018-07-15', false, false, false, true, false, false, false, 
			(SELECT curso.idcurso FROM curso WHERE curso.nome = 'Análise e Desenvolvimento de Sistemas')),
		('Cálculos de Finanças Pessoais e Corporativas', '2018-07-24', '2018-10-10', false, false, true, false, false, false, false, 
			(SELECT curso.idcurso FROM curso WHERE curso.nome = 'Análise e Desenvolvimento de Sistemas')),
		('Projeto Integrador III - Software Básico', '2018-07-24', '2018-10-10', false, false, false, true, false, false, false, 
			(SELECT curso.idcurso FROM curso WHERE curso.nome = 'Análise e Desenvolvimento de Sistemas')),
		('Sistemas Operacionais', '2018-07-24', '2018-10-10', false, false, false, false, false, true, false, 
			(SELECT curso.idcurso FROM curso WHERE curso.nome = 'Análise e Desenvolvimento de Sistemas'));
			
INSERT INTO tarefa(nome, data, hora, descricao, status, iddisciplina) 
VALUES 	('Questionário Unidade 1', '07/03/2018', '22:00', 'Responder ao questionário', true, 1),
		('Questionário Unidade 2', '14/03/2018', '22:00', 'Responder ao questionário', true, 1),
		('Questionário Unidade 3', '21/03/2018', '22:00', 'Responder ao questionário', true, 1),
		('Questionário Unidade 4', '28/03/2018', '22:00', 'Responder ao questionário', true, 1),
		('Atividade Unidade 4', '28/03/2018', '22:00', 'Com base no que você aprendeu até aqui e na leitura do capítulo Lógica matemática, páginas 19 a 22, do livro Raciocínio lógico e lógica quantitativa, realize a atividade.', true, 1),
		('Questionário: Coesão e Coerência', '26/03/2018', '22:00', 'Na atividade referente à Unidade 2, vamos explorar os mecanismos de coesão que contribuem para construirmos a coerência de um texto.', true, 2),
		('Questionário: Estratégias de Leitura', '02/04/2018', '22:00', 'A proposta está dividida em duas etapas: a primeira refere-se à pré-leitura de 3 textos (leitura top-down) enquanto que a segunda diz respeito a uma leitura detalhada (leitura bottom-up) de cada um deles. As questões de 1 a 3 fazem parte da pré-leitura. Nessa etapa, você deve ler os textos indicados em cada questão e observar o que está em torno deles: título, local de publicação, data, seção, autor etc. Considerando essas pistas, responda às questões, assinalando a alternativa que expressa a hipótese mais provável. Já as questões de 4 a 8 exigirão uma leitura mais atenta. Após ler e compreender o texto, responda o que é solicitado em cada uma delas.', true, 2),
		('Tarefa: Produção de resumo', '09/04/2018', '22:00', 'Agora que você conheceu algumas estratégias para sumarizar e parafrasear um texto, você vai praticá-las por meio da elaboração de um resumo.', true, 2);
		

INSERT INTO subtarefa(nome, status, idtarefa)
VALUES 	('Questão 1', false, 1),
		('Questão 2', true, 1),
		('Questão 3', true, 1),
		('Questão 4', true, 1),
		('Questão 5', false, 1),
		('Questão 6', false, 1),
		('Questão 7', true, 1),
		('Questão 8', true, 1),
		('Questão 1', true, 2),
		('Questão 2', true, 2),
		('Questão 3', false, 2),
		('Questão 4', false, 2),
		('Questão 5', false, 2),
		('Questão 1', false, 3),
		('Questão 2', false, 3),
		('Questão 3', false, 3),
		('Questão 4', false, 3),
		('Questão 5', false, 3),
		('Questão 6', false, 3),
		('Questão 1', true, 4),
		('Questão 2', true, 4),
		('Questão 3', true, 4),
		('Questão 4', true, 4),
		('Questão 5', true, 4),
		('Realizar atividade', false, 5),
		('Questão 1', true, 6),
		('Questão 2', false, 6),
		('Questão 3', false, 6),
		('Questão 4', true, 6),
		('Questão 5', true, 6),
		('Questão 1', false, 7),
		('Questão 2', false, 7),
		('Questão 3', false, 7),
		('Questão 4', false, 7),
		('Questão 5', false, 7),
		('Questão 6', false, 7),
		('Questão 7', false, 7),
		('Questão 8', false, 7),
		('Etapa 1', true, 8),
		('Etapa 2', true, 8),
		('Etapa 3', true, 8);
		